// Copyright 2018-2024 opcua authors. All rights reserved.
// Use of this source code is governed by a MIT-style license that can be
// found in the LICENSE file.

package main

import (
	"bytes"
	"encoding/csv"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"text/template"
)

type nodePermission struct {
	NodeID             uint32
	AccessRestrictions uint16
	RolePermissions    []rolePermission
}

type rolePermission struct {
	RoleName    string
	Permissions uint32
}

func main() {
	log.SetFlags(0)

	in := flag.String("in", "schema/Opc.Ua.NodeIds.permissions.csv", "path to permissions CSV")
	out := flag.String("out", "server/default_permissions_gen.go", "path to generated file")
	flag.Parse()

	if *in == "" {
		log.Fatal("-in is required")
	}
	if *out == "" {
		log.Fatal("-out is required")
	}

	f, err := os.Open(*in)
	if err != nil {
		log.Fatalf("Error reading %s: %v", *in, err)
	}
	defer f.Close()

	rows, err := csv.NewReader(f).ReadAll()
	if err != nil {
		log.Fatalf("Error parsing %s: %v", *in, err)
	}

	var entries []nodePermission
	for _, row := range rows {
		if len(row) < 5 {
			continue
		}
		nodeID, err := strconv.ParseUint(row[1], 10, 32)
		if err != nil {
			log.Printf("Skipping %s: invalid node ID %q", row[0], row[1])
			continue
		}

		ar := parseAccessRestrictions(row[3])
		rps := parseRolePermissions(row[4])
		if len(rps) == 0 {
			continue
		}

		entries = append(entries, nodePermission{
			NodeID:             uint32(nodeID),
			AccessRestrictions: ar,
			RolePermissions:    rps,
		})
	}

	sort.Slice(entries, func(i, j int) bool {
		return entries[i].NodeID < entries[j].NodeID
	})

	var b bytes.Buffer
	if err := tmpl.Execute(&b, entries); err != nil {
		log.Fatalf("Error generating code: %v", err)
	}

	bfmt, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatalf("Error formatting code: %v", err)
	}

	if err := os.WriteFile(*out, bfmt, 0644); err != nil {
		log.Fatalf("Error writing %s: %v", *out, err)
	}
	log.Printf("Wrote %s (%d entries)", *out, len(entries))
}

// parseAccessRestrictions parses "[SigningRequired,EncryptionRequired]" style values.
func parseAccessRestrictions(s string) uint16 {
	s = strings.TrimSpace(s)
	if s == "" {
		return 0
	}
	s = strings.Trim(s, "[]")
	var result uint16
	for _, part := range strings.Split(s, ",") {
		switch strings.TrimSpace(part) {
		case "SigningRequired":
			result |= 1
		case "EncryptionRequired":
			result |= 2
		case "SessionRequired":
			result |= 4
		case "ApplyRestrictionsToBrowse":
			result |= 8
		}
	}
	return result
}

// rolePermRe matches entries like 'Anonymous':'(33) Browse|Read'
var rolePermRe = regexp.MustCompile(`'(\w+)':'(?:\((\d+)\)[^']*)'`)

// parseRolePermissions parses "{'Anonymous':'(33) Browse|Read','SecurityAdmin':'(131071) All'}"
func parseRolePermissions(s string) []rolePermission {
	matches := rolePermRe.FindAllStringSubmatch(s, -1)
	if len(matches) == 0 {
		return nil
	}
	var rps []rolePermission
	for _, m := range matches {
		roleName := m[1]
		permVal, err := strconv.ParseUint(m[2], 10, 32)
		if err != nil {
			log.Printf("Skipping role %s: invalid permission value %q", roleName, m[2])
			continue
		}
		rps = append(rps, rolePermission{
			RoleName:    roleName,
			Permissions: uint32(permVal),
		})
	}
	// Sort for deterministic output
	sort.Slice(rps, func(i, j int) bool {
		return rps[i].RoleName < rps[j].RoleName
	})
	return rps
}

var funcMap = template.FuncMap{
	"hex": func(v uint32) string { return fmt.Sprintf("0x%05x", v) },
}

var tmpl = template.Must(template.New("").Funcs(funcMap).Parse(`
// Copyright 2018-2024 opcua authors. All rights reserved.
// Use of this source code is governed by a MIT-style license that can be
// found in the LICENSE file.

// Code generated by cmd/permissions. DO NOT EDIT!

package server

import "github.com/otfabric/opcua/ua"

// NodePermissionDefault holds the default access restrictions and role
// permissions for a single standard node as defined by the OPC UA specification.
type NodePermissionDefault struct {
	AccessRestrictions ua.AccessRestrictionType
	RolePermissions    []ua.RolePermissionType
}

// DefaultNodePermissions maps namespace-0 node IDs to their default
// role-permission sets per the OPC UA specification.
var DefaultNodePermissions = map[uint32]NodePermissionDefault{
	{{- range .}}
	{{.NodeID}}: {
		AccessRestrictions: {{.AccessRestrictions}},
		RolePermissions: []ua.RolePermissionType{
			{{- range .RolePermissions}}
			{RoleID: roleNodeID("{{.RoleName}}"), Permissions: {{hex .Permissions}}},
			{{- end}}
		},
	},
	{{- end}}
}

func roleNodeID(name string) *ua.NodeID {
	role, ok := ua.RoleByName[name]
	if !ok {
		return ua.NewNumericNodeID(0, 0)
	}
	return role.NodeID()
}
`))
