// Copyright 2018-2024 opcua authors. All rights reserved.
// Use of this source code is governed by a MIT-style license that can be
// found in the LICENSE file.

package main

import (
	"bufio"
	"bytes"
	"flag"
	"go/format"
	"log"
	"os"
	"strings"
	"text/template"
	"unicode"
)

type entry struct {
	ID          string
	GoName      string
	Description string
}

func main() {
	log.SetFlags(0)

	in := flag.String("in", "schema/ServerCapabilities.csv", "path to ServerCapabilities.csv")
	out := flag.String("out", "ua/server_capabilities_gen.go", "path to generated file")
	flag.Parse()

	if *in == "" {
		log.Fatal("-in is required")
	}
	if *out == "" {
		log.Fatal("-out is required")
	}

	f, err := os.Open(*in)
	if err != nil {
		log.Fatalf("Error reading %s: %v", *in, err)
	}
	defer f.Close()

	var entries []entry
	sc := bufio.NewScanner(f)
	first := true
	for sc.Scan() {
		line := sc.Text()
		if first {
			line = strings.TrimPrefix(line, "\xef\xbb\xbf")
			first = false
		}
		parts := strings.SplitN(line, ",", 2)
		if len(parts) != 2 {
			continue
		}
		id := strings.TrimSpace(parts[0])
		desc := strings.TrimSpace(parts[1])
		goName := id
		if len(goName) > 0 && unicode.IsDigit(rune(goName[0])) {
			goName = "IEC" + goName
		}
		entries = append(entries, entry{
			ID:          id,
			GoName:      goName,
			Description: desc,
		})
	}
	if sc.Err() != nil {
		log.Fatalf("Error reading %s: %v", *in, sc.Err())
	}

	var b bytes.Buffer
	if err := tmpl.Execute(&b, entries); err != nil {
		log.Fatalf("Error generating code: %v", err)
	}

	bfmt, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatalf("Error formatting code: %v", err)
	}

	if err := os.WriteFile(*out, bfmt, 0644); err != nil {
		log.Fatalf("Error writing %s: %v", *out, err)
	}
	log.Printf("Wrote %s", *out)
}

var tmpl = template.Must(template.New("").Parse(`
// Copyright 2018-2024 opcua authors. All rights reserved.
// Use of this source code is governed by a MIT-style license that can be
// found in the LICENSE file.

// Code generated by cmd/capability. DO NOT EDIT!

package ua

// Server capability profile identifiers per OPC UA specification.
const (
	{{- range .}}
	// Capability{{.GoName}}: {{.Description}}
	Capability{{.GoName}} = "{{.ID}}"
	{{- end}}
)

// KnownCapabilities maps server capability identifiers to their descriptions.
var KnownCapabilities = map[string]string{
	{{- range .}}
	Capability{{.GoName}}: "{{.Description}}",
	{{- end}}
}

// ValidateCapability reports whether s is a known server capability identifier.
func ValidateCapability(s string) bool {
	_, ok := KnownCapabilities[s]
	return ok
}
`))
