// Code generated by "stringer -type NodeIDType,NamingRuleType,RedundantServerMode,OpenFileMode,IdentityCriteriaType,ConversionLimitEnum,AlarmMask,TrustListValidationOptions,TrustListMasks,ConfigurationUpdateType,PubSubState,DataSetFieldFlags,ActionState,DataSetFieldContentMask,OverrideValueHandling,DataSetOrderingType,UADPNetworkMessageContentMask,UADPDataSetMessageContentMask,JSONNetworkMessageContentMask,JSONDataSetMessageContentMask,BrokerTransportQoS,PubSubConfigurationRefMask,DiagnosticsLevel,PubSubDiagnosticsCounterClassification,PasswordOptionsMask,UserConfigurationMask,Duplex,InterfaceAdminStatus,InterfaceOperStatus,NegotiationStatus,TsnFailureCode,TsnStreamState,TsnTalkerStatus,TsnListenerStatus,ChassisIDSubtype,PortIDSubtype,ManAddrIfSubtype,LldpSystemCapabilitiesMap,LogRecordMask,IDType,NodeClass,PermissionType,AccessLevelType,AccessLevelExType,EventNotifierType,AccessRestrictionType,StructureType,ApplicationType,MessageSecurityMode,UserTokenType,SecurityTokenRequestType,NodeAttributesMask,AttributeWriteMask,BrowseDirection,BrowseResultMask,FilterOperator,TimestampsToReturn,SortOrderType,HistoryUpdateType,PerformUpdateType,MonitoringMode,DataChangeTrigger,DeadbandType,RedundancySupport,ServerState,ModelChangeStructureVerbMask,AxisScaleEnumeration,ExceptionDeviationFormat,AttributeID,TypeID -output enums_strings_gen.go"; DO NOT EDIT.

package ua

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NodeIDTypeTwoByte-0]
	_ = x[NodeIDTypeFourByte-1]
	_ = x[NodeIDTypeNumeric-2]
	_ = x[NodeIDTypeString-3]
	_ = x[NodeIDTypeGUID-4]
	_ = x[NodeIDTypeByteString-5]
}

const _NodeIDType_name = "NodeIDTypeTwoByteNodeIDTypeFourByteNodeIDTypeNumericNodeIDTypeStringNodeIDTypeGUIDNodeIDTypeByteString"

var _NodeIDType_index = [...]uint8{0, 17, 35, 52, 68, 82, 102}

func (i NodeIDType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_NodeIDType_index)-1 {
		return "NodeIDType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeIDType_name[_NodeIDType_index[idx]:_NodeIDType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NamingRuleTypeMandatory-1]
	_ = x[NamingRuleTypeOptional-2]
	_ = x[NamingRuleTypeConstraint-3]
}

const _NamingRuleType_name = "NamingRuleTypeMandatoryNamingRuleTypeOptionalNamingRuleTypeConstraint"

var _NamingRuleType_index = [...]uint8{0, 23, 45, 69}

func (i NamingRuleType) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_NamingRuleType_index)-1 {
		return "NamingRuleType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NamingRuleType_name[_NamingRuleType_index[idx]:_NamingRuleType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RedundantServerModePrimaryWithBackup-0]
	_ = x[RedundantServerModePrimaryOnly-1]
	_ = x[RedundantServerModeBackupReady-2]
	_ = x[RedundantServerModeBackupNotReady-3]
}

const _RedundantServerMode_name = "RedundantServerModePrimaryWithBackupRedundantServerModePrimaryOnlyRedundantServerModeBackupReadyRedundantServerModeBackupNotReady"

var _RedundantServerMode_index = [...]uint8{0, 36, 66, 96, 129}

func (i RedundantServerMode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RedundantServerMode_index)-1 {
		return "RedundantServerMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RedundantServerMode_name[_RedundantServerMode_index[idx]:_RedundantServerMode_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpenFileModeRead-1]
	_ = x[OpenFileModeWrite-2]
	_ = x[OpenFileModeEraseExisting-4]
	_ = x[OpenFileModeAppend-8]
}

const (
	_OpenFileMode_name_0 = "OpenFileModeReadOpenFileModeWrite"
	_OpenFileMode_name_1 = "OpenFileModeEraseExisting"
	_OpenFileMode_name_2 = "OpenFileModeAppend"
)

var (
	_OpenFileMode_index_0 = [...]uint8{0, 16, 33}
)

func (i OpenFileMode) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _OpenFileMode_name_0[_OpenFileMode_index_0[i]:_OpenFileMode_index_0[i+1]]
	case i == 4:
		return _OpenFileMode_name_1
	case i == 8:
		return _OpenFileMode_name_2
	default:
		return "OpenFileMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IdentityCriteriaTypeUserName-1]
	_ = x[IdentityCriteriaTypeThumbprint-2]
	_ = x[IdentityCriteriaTypeRole-3]
	_ = x[IdentityCriteriaTypeGroupID-4]
	_ = x[IdentityCriteriaTypeAnonymous-5]
	_ = x[IdentityCriteriaTypeAuthenticatedUser-6]
	_ = x[IdentityCriteriaTypeApplication-7]
	_ = x[IdentityCriteriaTypeX509Subject-8]
	_ = x[IdentityCriteriaTypeTrustedApplication-9]
}

const _IdentityCriteriaType_name = "IdentityCriteriaTypeUserNameIdentityCriteriaTypeThumbprintIdentityCriteriaTypeRoleIdentityCriteriaTypeGroupIDIdentityCriteriaTypeAnonymousIdentityCriteriaTypeAuthenticatedUserIdentityCriteriaTypeApplicationIdentityCriteriaTypeX509SubjectIdentityCriteriaTypeTrustedApplication"

var _IdentityCriteriaType_index = [...]uint16{0, 28, 58, 82, 109, 138, 175, 206, 237, 275}

func (i IdentityCriteriaType) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_IdentityCriteriaType_index)-1 {
		return "IdentityCriteriaType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IdentityCriteriaType_name[_IdentityCriteriaType_index[idx]:_IdentityCriteriaType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ConversionLimitEnumNoConversion-0]
	_ = x[ConversionLimitEnumLimited-1]
	_ = x[ConversionLimitEnumUnlimited-2]
}

const _ConversionLimitEnum_name = "ConversionLimitEnumNoConversionConversionLimitEnumLimitedConversionLimitEnumUnlimited"

var _ConversionLimitEnum_index = [...]uint8{0, 31, 57, 85}

func (i ConversionLimitEnum) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ConversionLimitEnum_index)-1 {
		return "ConversionLimitEnum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConversionLimitEnum_name[_ConversionLimitEnum_index[idx]:_ConversionLimitEnum_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AlarmMaskNone-0]
	_ = x[AlarmMaskActive-1]
	_ = x[AlarmMaskUnacknowledged-2]
	_ = x[AlarmMaskUnconfirmed-4]
}

const (
	_AlarmMask_name_0 = "AlarmMaskNoneAlarmMaskActiveAlarmMaskUnacknowledged"
	_AlarmMask_name_1 = "AlarmMaskUnconfirmed"
)

var (
	_AlarmMask_index_0 = [...]uint8{0, 13, 28, 51}
)

func (i AlarmMask) String() string {
	switch {
	case i <= 2:
		return _AlarmMask_name_0[_AlarmMask_index_0[i]:_AlarmMask_index_0[i+1]]
	case i == 4:
		return _AlarmMask_name_1
	default:
		return "AlarmMask(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TrustListValidationOptionsNone-0]
	_ = x[TrustListValidationOptionsSuppressCertificateExpired-1]
	_ = x[TrustListValidationOptionsSuppressHostNameInvalid-2]
	_ = x[TrustListValidationOptionsSuppressRevocationStatusUnknown-4]
	_ = x[TrustListValidationOptionsSuppressIssuerCertificateExpired-8]
	_ = x[TrustListValidationOptionsSuppressIssuerRevocationStatusUnknown-16]
	_ = x[TrustListValidationOptionsCheckRevocationStatusOnline-32]
	_ = x[TrustListValidationOptionsCheckRevocationStatusOffline-64]
}

const (
	_TrustListValidationOptions_name_0 = "TrustListValidationOptionsNoneTrustListValidationOptionsSuppressCertificateExpiredTrustListValidationOptionsSuppressHostNameInvalid"
	_TrustListValidationOptions_name_1 = "TrustListValidationOptionsSuppressRevocationStatusUnknown"
	_TrustListValidationOptions_name_2 = "TrustListValidationOptionsSuppressIssuerCertificateExpired"
	_TrustListValidationOptions_name_3 = "TrustListValidationOptionsSuppressIssuerRevocationStatusUnknown"
	_TrustListValidationOptions_name_4 = "TrustListValidationOptionsCheckRevocationStatusOnline"
	_TrustListValidationOptions_name_5 = "TrustListValidationOptionsCheckRevocationStatusOffline"
)

var (
	_TrustListValidationOptions_index_0 = [...]uint8{0, 30, 82, 131}
)

func (i TrustListValidationOptions) String() string {
	switch {
	case i <= 2:
		return _TrustListValidationOptions_name_0[_TrustListValidationOptions_index_0[i]:_TrustListValidationOptions_index_0[i+1]]
	case i == 4:
		return _TrustListValidationOptions_name_1
	case i == 8:
		return _TrustListValidationOptions_name_2
	case i == 16:
		return _TrustListValidationOptions_name_3
	case i == 32:
		return _TrustListValidationOptions_name_4
	case i == 64:
		return _TrustListValidationOptions_name_5
	default:
		return "TrustListValidationOptions(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TrustListMasksNone-0]
	_ = x[TrustListMasksTrustedCertificates-1]
	_ = x[TrustListMasksTrustedCrls-2]
	_ = x[TrustListMasksIssuerCertificates-4]
	_ = x[TrustListMasksIssuerCrls-8]
	_ = x[TrustListMasksAll-15]
}

const (
	_TrustListMasks_name_0 = "TrustListMasksNoneTrustListMasksTrustedCertificatesTrustListMasksTrustedCrls"
	_TrustListMasks_name_1 = "TrustListMasksIssuerCertificates"
	_TrustListMasks_name_2 = "TrustListMasksIssuerCrls"
	_TrustListMasks_name_3 = "TrustListMasksAll"
)

var (
	_TrustListMasks_index_0 = [...]uint8{0, 18, 51, 76}
)

func (i TrustListMasks) String() string {
	switch {
	case i <= 2:
		return _TrustListMasks_name_0[_TrustListMasks_index_0[i]:_TrustListMasks_index_0[i+1]]
	case i == 4:
		return _TrustListMasks_name_1
	case i == 8:
		return _TrustListMasks_name_2
	case i == 15:
		return _TrustListMasks_name_3
	default:
		return "TrustListMasks(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ConfigurationUpdateTypeInsert-1]
	_ = x[ConfigurationUpdateTypeReplace-2]
	_ = x[ConfigurationUpdateTypeInsertOrReplace-3]
	_ = x[ConfigurationUpdateTypeDelete-4]
}

const _ConfigurationUpdateType_name = "ConfigurationUpdateTypeInsertConfigurationUpdateTypeReplaceConfigurationUpdateTypeInsertOrReplaceConfigurationUpdateTypeDelete"

var _ConfigurationUpdateType_index = [...]uint8{0, 29, 59, 97, 126}

func (i ConfigurationUpdateType) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_ConfigurationUpdateType_index)-1 {
		return "ConfigurationUpdateType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConfigurationUpdateType_name[_ConfigurationUpdateType_index[idx]:_ConfigurationUpdateType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PubSubStateDisabled-0]
	_ = x[PubSubStatePaused-1]
	_ = x[PubSubStateOperational-2]
	_ = x[PubSubStateError-3]
	_ = x[PubSubStatePreOperational-4]
}

const _PubSubState_name = "PubSubStateDisabledPubSubStatePausedPubSubStateOperationalPubSubStateErrorPubSubStatePreOperational"

var _PubSubState_index = [...]uint8{0, 19, 36, 58, 74, 99}

func (i PubSubState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PubSubState_index)-1 {
		return "PubSubState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PubSubState_name[_PubSubState_index[idx]:_PubSubState_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DataSetFieldFlagsNone-0]
	_ = x[DataSetFieldFlagsPromotedField-1]
}

const _DataSetFieldFlags_name = "DataSetFieldFlagsNoneDataSetFieldFlagsPromotedField"

var _DataSetFieldFlags_index = [...]uint8{0, 21, 51}

func (i DataSetFieldFlags) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_DataSetFieldFlags_index)-1 {
		return "DataSetFieldFlags(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataSetFieldFlags_name[_DataSetFieldFlags_index[idx]:_DataSetFieldFlags_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ActionStateIDle-0]
	_ = x[ActionStateExecuting-1]
	_ = x[ActionStateDone-2]
}

const _ActionState_name = "ActionStateIDleActionStateExecutingActionStateDone"

var _ActionState_index = [...]uint8{0, 15, 35, 50}

func (i ActionState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ActionState_index)-1 {
		return "ActionState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ActionState_name[_ActionState_index[idx]:_ActionState_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DataSetFieldContentMaskNone-0]
	_ = x[DataSetFieldContentMaskStatusCode-1]
	_ = x[DataSetFieldContentMaskSourceTimestamp-2]
	_ = x[DataSetFieldContentMaskServerTimestamp-4]
	_ = x[DataSetFieldContentMaskSourcePicoSeconds-8]
	_ = x[DataSetFieldContentMaskServerPicoSeconds-16]
	_ = x[DataSetFieldContentMaskRawData-32]
}

const (
	_DataSetFieldContentMask_name_0 = "DataSetFieldContentMaskNoneDataSetFieldContentMaskStatusCodeDataSetFieldContentMaskSourceTimestamp"
	_DataSetFieldContentMask_name_1 = "DataSetFieldContentMaskServerTimestamp"
	_DataSetFieldContentMask_name_2 = "DataSetFieldContentMaskSourcePicoSeconds"
	_DataSetFieldContentMask_name_3 = "DataSetFieldContentMaskServerPicoSeconds"
	_DataSetFieldContentMask_name_4 = "DataSetFieldContentMaskRawData"
)

var (
	_DataSetFieldContentMask_index_0 = [...]uint8{0, 27, 60, 98}
)

func (i DataSetFieldContentMask) String() string {
	switch {
	case i <= 2:
		return _DataSetFieldContentMask_name_0[_DataSetFieldContentMask_index_0[i]:_DataSetFieldContentMask_index_0[i+1]]
	case i == 4:
		return _DataSetFieldContentMask_name_1
	case i == 8:
		return _DataSetFieldContentMask_name_2
	case i == 16:
		return _DataSetFieldContentMask_name_3
	case i == 32:
		return _DataSetFieldContentMask_name_4
	default:
		return "DataSetFieldContentMask(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OverrideValueHandlingDisabled-0]
	_ = x[OverrideValueHandlingLastUsableValue-1]
	_ = x[OverrideValueHandlingOverrideValue-2]
}

const _OverrideValueHandling_name = "OverrideValueHandlingDisabledOverrideValueHandlingLastUsableValueOverrideValueHandlingOverrideValue"

var _OverrideValueHandling_index = [...]uint8{0, 29, 65, 99}

func (i OverrideValueHandling) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_OverrideValueHandling_index)-1 {
		return "OverrideValueHandling(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OverrideValueHandling_name[_OverrideValueHandling_index[idx]:_OverrideValueHandling_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DataSetOrderingTypeUndefined-0]
	_ = x[DataSetOrderingTypeAscendingWriterID-1]
	_ = x[DataSetOrderingTypeAscendingWriterIDSingle-2]
}

const _DataSetOrderingType_name = "DataSetOrderingTypeUndefinedDataSetOrderingTypeAscendingWriterIDDataSetOrderingTypeAscendingWriterIDSingle"

var _DataSetOrderingType_index = [...]uint8{0, 28, 64, 106}

func (i DataSetOrderingType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_DataSetOrderingType_index)-1 {
		return "DataSetOrderingType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataSetOrderingType_name[_DataSetOrderingType_index[idx]:_DataSetOrderingType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UADPNetworkMessageContentMaskNone-0]
	_ = x[UADPNetworkMessageContentMaskPublisherID-1]
	_ = x[UADPNetworkMessageContentMaskGroupHeader-2]
	_ = x[UADPNetworkMessageContentMaskWriterGroupID-4]
	_ = x[UADPNetworkMessageContentMaskGroupVersion-8]
	_ = x[UADPNetworkMessageContentMaskNetworkMessageNumber-16]
	_ = x[UADPNetworkMessageContentMaskSequenceNumber-32]
	_ = x[UADPNetworkMessageContentMaskPayloadHeader-64]
	_ = x[UADPNetworkMessageContentMaskTimestamp-128]
	_ = x[UADPNetworkMessageContentMaskPicoSeconds-256]
	_ = x[UADPNetworkMessageContentMaskDataSetClassID-512]
	_ = x[UADPNetworkMessageContentMaskPromotedFields-1024]
}

const (
	_UADPNetworkMessageContentMask_name_0 = "UADPNetworkMessageContentMaskNoneUADPNetworkMessageContentMaskPublisherIDUADPNetworkMessageContentMaskGroupHeader"
	_UADPNetworkMessageContentMask_name_1 = "UADPNetworkMessageContentMaskWriterGroupID"
	_UADPNetworkMessageContentMask_name_2 = "UADPNetworkMessageContentMaskGroupVersion"
	_UADPNetworkMessageContentMask_name_3 = "UADPNetworkMessageContentMaskNetworkMessageNumber"
	_UADPNetworkMessageContentMask_name_4 = "UADPNetworkMessageContentMaskSequenceNumber"
	_UADPNetworkMessageContentMask_name_5 = "UADPNetworkMessageContentMaskPayloadHeader"
	_UADPNetworkMessageContentMask_name_6 = "UADPNetworkMessageContentMaskTimestamp"
	_UADPNetworkMessageContentMask_name_7 = "UADPNetworkMessageContentMaskPicoSeconds"
	_UADPNetworkMessageContentMask_name_8 = "UADPNetworkMessageContentMaskDataSetClassID"
	_UADPNetworkMessageContentMask_name_9 = "UADPNetworkMessageContentMaskPromotedFields"
)

var (
	_UADPNetworkMessageContentMask_index_0 = [...]uint8{0, 33, 73, 113}
)

func (i UADPNetworkMessageContentMask) String() string {
	switch {
	case i <= 2:
		return _UADPNetworkMessageContentMask_name_0[_UADPNetworkMessageContentMask_index_0[i]:_UADPNetworkMessageContentMask_index_0[i+1]]
	case i == 4:
		return _UADPNetworkMessageContentMask_name_1
	case i == 8:
		return _UADPNetworkMessageContentMask_name_2
	case i == 16:
		return _UADPNetworkMessageContentMask_name_3
	case i == 32:
		return _UADPNetworkMessageContentMask_name_4
	case i == 64:
		return _UADPNetworkMessageContentMask_name_5
	case i == 128:
		return _UADPNetworkMessageContentMask_name_6
	case i == 256:
		return _UADPNetworkMessageContentMask_name_7
	case i == 512:
		return _UADPNetworkMessageContentMask_name_8
	case i == 1024:
		return _UADPNetworkMessageContentMask_name_9
	default:
		return "UADPNetworkMessageContentMask(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UADPDataSetMessageContentMaskNone-0]
	_ = x[UADPDataSetMessageContentMaskTimestamp-1]
	_ = x[UADPDataSetMessageContentMaskPicoSeconds-2]
	_ = x[UADPDataSetMessageContentMaskStatus-4]
	_ = x[UADPDataSetMessageContentMaskMajorVersion-8]
	_ = x[UADPDataSetMessageContentMaskMinorVersion-16]
	_ = x[UADPDataSetMessageContentMaskSequenceNumber-32]
}

const (
	_UADPDataSetMessageContentMask_name_0 = "UADPDataSetMessageContentMaskNoneUADPDataSetMessageContentMaskTimestampUADPDataSetMessageContentMaskPicoSeconds"
	_UADPDataSetMessageContentMask_name_1 = "UADPDataSetMessageContentMaskStatus"
	_UADPDataSetMessageContentMask_name_2 = "UADPDataSetMessageContentMaskMajorVersion"
	_UADPDataSetMessageContentMask_name_3 = "UADPDataSetMessageContentMaskMinorVersion"
	_UADPDataSetMessageContentMask_name_4 = "UADPDataSetMessageContentMaskSequenceNumber"
)

var (
	_UADPDataSetMessageContentMask_index_0 = [...]uint8{0, 33, 71, 111}
)

func (i UADPDataSetMessageContentMask) String() string {
	switch {
	case i <= 2:
		return _UADPDataSetMessageContentMask_name_0[_UADPDataSetMessageContentMask_index_0[i]:_UADPDataSetMessageContentMask_index_0[i+1]]
	case i == 4:
		return _UADPDataSetMessageContentMask_name_1
	case i == 8:
		return _UADPDataSetMessageContentMask_name_2
	case i == 16:
		return _UADPDataSetMessageContentMask_name_3
	case i == 32:
		return _UADPDataSetMessageContentMask_name_4
	default:
		return "UADPDataSetMessageContentMask(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[JSONNetworkMessageContentMaskNone-0]
	_ = x[JSONNetworkMessageContentMaskNetworkMessageHeader-1]
	_ = x[JSONNetworkMessageContentMaskDataSetMessageHeader-2]
	_ = x[JSONNetworkMessageContentMaskSingleDataSetMessage-4]
	_ = x[JSONNetworkMessageContentMaskPublisherID-8]
	_ = x[JSONNetworkMessageContentMaskDataSetClassID-16]
	_ = x[JSONNetworkMessageContentMaskReplyTo-32]
	_ = x[JSONNetworkMessageContentMaskWriterGroupName-64]
}

const (
	_JSONNetworkMessageContentMask_name_0 = "JSONNetworkMessageContentMaskNoneJSONNetworkMessageContentMaskNetworkMessageHeaderJSONNetworkMessageContentMaskDataSetMessageHeader"
	_JSONNetworkMessageContentMask_name_1 = "JSONNetworkMessageContentMaskSingleDataSetMessage"
	_JSONNetworkMessageContentMask_name_2 = "JSONNetworkMessageContentMaskPublisherID"
	_JSONNetworkMessageContentMask_name_3 = "JSONNetworkMessageContentMaskDataSetClassID"
	_JSONNetworkMessageContentMask_name_4 = "JSONNetworkMessageContentMaskReplyTo"
	_JSONNetworkMessageContentMask_name_5 = "JSONNetworkMessageContentMaskWriterGroupName"
)

var (
	_JSONNetworkMessageContentMask_index_0 = [...]uint8{0, 33, 82, 131}
)

func (i JSONNetworkMessageContentMask) String() string {
	switch {
	case i <= 2:
		return _JSONNetworkMessageContentMask_name_0[_JSONNetworkMessageContentMask_index_0[i]:_JSONNetworkMessageContentMask_index_0[i+1]]
	case i == 4:
		return _JSONNetworkMessageContentMask_name_1
	case i == 8:
		return _JSONNetworkMessageContentMask_name_2
	case i == 16:
		return _JSONNetworkMessageContentMask_name_3
	case i == 32:
		return _JSONNetworkMessageContentMask_name_4
	case i == 64:
		return _JSONNetworkMessageContentMask_name_5
	default:
		return "JSONNetworkMessageContentMask(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[JSONDataSetMessageContentMaskNone-0]
	_ = x[JSONDataSetMessageContentMaskDataSetWriterID-1]
	_ = x[JSONDataSetMessageContentMaskMetaDataVersion-2]
	_ = x[JSONDataSetMessageContentMaskSequenceNumber-4]
	_ = x[JSONDataSetMessageContentMaskTimestamp-8]
	_ = x[JSONDataSetMessageContentMaskStatus-16]
	_ = x[JSONDataSetMessageContentMaskMessageType-32]
	_ = x[JSONDataSetMessageContentMaskDataSetWriterName-64]
	_ = x[JSONDataSetMessageContentMaskFieldEncoding1-128]
	_ = x[JSONDataSetMessageContentMaskPublisherID-256]
	_ = x[JSONDataSetMessageContentMaskWriterGroupName-512]
	_ = x[JSONDataSetMessageContentMaskMinorVersion-1024]
	_ = x[JSONDataSetMessageContentMaskFieldEncoding2-2048]
}

const _JSONDataSetMessageContentMask_name = "JSONDataSetMessageContentMaskNoneJSONDataSetMessageContentMaskDataSetWriterIDJSONDataSetMessageContentMaskMetaDataVersionJSONDataSetMessageContentMaskSequenceNumberJSONDataSetMessageContentMaskTimestampJSONDataSetMessageContentMaskStatusJSONDataSetMessageContentMaskMessageTypeJSONDataSetMessageContentMaskDataSetWriterNameJSONDataSetMessageContentMaskFieldEncoding1JSONDataSetMessageContentMaskPublisherIDJSONDataSetMessageContentMaskWriterGroupNameJSONDataSetMessageContentMaskMinorVersionJSONDataSetMessageContentMaskFieldEncoding2"

var _JSONDataSetMessageContentMask_map = map[JSONDataSetMessageContentMask]string{
	0:    _JSONDataSetMessageContentMask_name[0:33],
	1:    _JSONDataSetMessageContentMask_name[33:77],
	2:    _JSONDataSetMessageContentMask_name[77:121],
	4:    _JSONDataSetMessageContentMask_name[121:164],
	8:    _JSONDataSetMessageContentMask_name[164:202],
	16:   _JSONDataSetMessageContentMask_name[202:237],
	32:   _JSONDataSetMessageContentMask_name[237:277],
	64:   _JSONDataSetMessageContentMask_name[277:323],
	128:  _JSONDataSetMessageContentMask_name[323:366],
	256:  _JSONDataSetMessageContentMask_name[366:406],
	512:  _JSONDataSetMessageContentMask_name[406:450],
	1024: _JSONDataSetMessageContentMask_name[450:491],
	2048: _JSONDataSetMessageContentMask_name[491:534],
}

func (i JSONDataSetMessageContentMask) String() string {
	if str, ok := _JSONDataSetMessageContentMask_map[i]; ok {
		return str
	}
	return "JSONDataSetMessageContentMask(" + strconv.FormatInt(int64(i), 10) + ")"
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BrokerTransportQoSNotSpecified-0]
	_ = x[BrokerTransportQoSBestEffort-1]
	_ = x[BrokerTransportQoSAtLeastOnce-2]
	_ = x[BrokerTransportQoSAtMostOnce-3]
	_ = x[BrokerTransportQoSExactlyOnce-4]
}

const _BrokerTransportQoS_name = "BrokerTransportQoSNotSpecifiedBrokerTransportQoSBestEffortBrokerTransportQoSAtLeastOnceBrokerTransportQoSAtMostOnceBrokerTransportQoSExactlyOnce"

var _BrokerTransportQoS_index = [...]uint8{0, 30, 58, 87, 115, 144}

func (i BrokerTransportQoS) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_BrokerTransportQoS_index)-1 {
		return "BrokerTransportQoS(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BrokerTransportQoS_name[_BrokerTransportQoS_index[idx]:_BrokerTransportQoS_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PubSubConfigurationRefMaskNone-0]
	_ = x[PubSubConfigurationRefMaskElementAdd-1]
	_ = x[PubSubConfigurationRefMaskElementMatch-2]
	_ = x[PubSubConfigurationRefMaskElementModify-4]
	_ = x[PubSubConfigurationRefMaskElementRemove-8]
	_ = x[PubSubConfigurationRefMaskReferenceWriter-16]
	_ = x[PubSubConfigurationRefMaskReferenceReader-32]
	_ = x[PubSubConfigurationRefMaskReferenceWriterGroup-64]
	_ = x[PubSubConfigurationRefMaskReferenceReaderGroup-128]
	_ = x[PubSubConfigurationRefMaskReferenceConnection-256]
	_ = x[PubSubConfigurationRefMaskReferencePubDataset-512]
	_ = x[PubSubConfigurationRefMaskReferenceSubDataset-1024]
	_ = x[PubSubConfigurationRefMaskReferenceSecurityGroup-2048]
	_ = x[PubSubConfigurationRefMaskReferencePushTarget-4096]
}

const _PubSubConfigurationRefMask_name = "PubSubConfigurationRefMaskNonePubSubConfigurationRefMaskElementAddPubSubConfigurationRefMaskElementMatchPubSubConfigurationRefMaskElementModifyPubSubConfigurationRefMaskElementRemovePubSubConfigurationRefMaskReferenceWriterPubSubConfigurationRefMaskReferenceReaderPubSubConfigurationRefMaskReferenceWriterGroupPubSubConfigurationRefMaskReferenceReaderGroupPubSubConfigurationRefMaskReferenceConnectionPubSubConfigurationRefMaskReferencePubDatasetPubSubConfigurationRefMaskReferenceSubDatasetPubSubConfigurationRefMaskReferenceSecurityGroupPubSubConfigurationRefMaskReferencePushTarget"

var _PubSubConfigurationRefMask_map = map[PubSubConfigurationRefMask]string{
	0:    _PubSubConfigurationRefMask_name[0:30],
	1:    _PubSubConfigurationRefMask_name[30:66],
	2:    _PubSubConfigurationRefMask_name[66:104],
	4:    _PubSubConfigurationRefMask_name[104:143],
	8:    _PubSubConfigurationRefMask_name[143:182],
	16:   _PubSubConfigurationRefMask_name[182:223],
	32:   _PubSubConfigurationRefMask_name[223:264],
	64:   _PubSubConfigurationRefMask_name[264:310],
	128:  _PubSubConfigurationRefMask_name[310:356],
	256:  _PubSubConfigurationRefMask_name[356:401],
	512:  _PubSubConfigurationRefMask_name[401:446],
	1024: _PubSubConfigurationRefMask_name[446:491],
	2048: _PubSubConfigurationRefMask_name[491:539],
	4096: _PubSubConfigurationRefMask_name[539:584],
}

func (i PubSubConfigurationRefMask) String() string {
	if str, ok := _PubSubConfigurationRefMask_map[i]; ok {
		return str
	}
	return "PubSubConfigurationRefMask(" + strconv.FormatInt(int64(i), 10) + ")"
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DiagnosticsLevelBasic-0]
	_ = x[DiagnosticsLevelAdvanced-1]
	_ = x[DiagnosticsLevelInfo-2]
	_ = x[DiagnosticsLevelLog-3]
	_ = x[DiagnosticsLevelDebug-4]
}

const _DiagnosticsLevel_name = "DiagnosticsLevelBasicDiagnosticsLevelAdvancedDiagnosticsLevelInfoDiagnosticsLevelLogDiagnosticsLevelDebug"

var _DiagnosticsLevel_index = [...]uint8{0, 21, 45, 65, 84, 105}

func (i DiagnosticsLevel) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_DiagnosticsLevel_index)-1 {
		return "DiagnosticsLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DiagnosticsLevel_name[_DiagnosticsLevel_index[idx]:_DiagnosticsLevel_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PubSubDiagnosticsCounterClassificationInformation-0]
	_ = x[PubSubDiagnosticsCounterClassificationError-1]
}

const _PubSubDiagnosticsCounterClassification_name = "PubSubDiagnosticsCounterClassificationInformationPubSubDiagnosticsCounterClassificationError"

var _PubSubDiagnosticsCounterClassification_index = [...]uint8{0, 49, 92}

func (i PubSubDiagnosticsCounterClassification) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PubSubDiagnosticsCounterClassification_index)-1 {
		return "PubSubDiagnosticsCounterClassification(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PubSubDiagnosticsCounterClassification_name[_PubSubDiagnosticsCounterClassification_index[idx]:_PubSubDiagnosticsCounterClassification_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PasswordOptionsMaskNone-0]
	_ = x[PasswordOptionsMaskSupportInitialPasswordChange-1]
	_ = x[PasswordOptionsMaskSupportDisableUser-2]
	_ = x[PasswordOptionsMaskSupportDisableDeleteForUser-4]
	_ = x[PasswordOptionsMaskSupportNoChangeForUser-8]
	_ = x[PasswordOptionsMaskSupportDescriptionForUser-16]
	_ = x[PasswordOptionsMaskRequiresUpperCaseCharacters-32]
	_ = x[PasswordOptionsMaskRequiresLowerCaseCharacters-64]
	_ = x[PasswordOptionsMaskRequiresDigitCharacters-128]
	_ = x[PasswordOptionsMaskRequiresSpecialCharacters-256]
}

const (
	_PasswordOptionsMask_name_0 = "PasswordOptionsMaskNonePasswordOptionsMaskSupportInitialPasswordChangePasswordOptionsMaskSupportDisableUser"
	_PasswordOptionsMask_name_1 = "PasswordOptionsMaskSupportDisableDeleteForUser"
	_PasswordOptionsMask_name_2 = "PasswordOptionsMaskSupportNoChangeForUser"
	_PasswordOptionsMask_name_3 = "PasswordOptionsMaskSupportDescriptionForUser"
	_PasswordOptionsMask_name_4 = "PasswordOptionsMaskRequiresUpperCaseCharacters"
	_PasswordOptionsMask_name_5 = "PasswordOptionsMaskRequiresLowerCaseCharacters"
	_PasswordOptionsMask_name_6 = "PasswordOptionsMaskRequiresDigitCharacters"
	_PasswordOptionsMask_name_7 = "PasswordOptionsMaskRequiresSpecialCharacters"
)

var (
	_PasswordOptionsMask_index_0 = [...]uint8{0, 23, 70, 107}
)

func (i PasswordOptionsMask) String() string {
	switch {
	case i <= 2:
		return _PasswordOptionsMask_name_0[_PasswordOptionsMask_index_0[i]:_PasswordOptionsMask_index_0[i+1]]
	case i == 4:
		return _PasswordOptionsMask_name_1
	case i == 8:
		return _PasswordOptionsMask_name_2
	case i == 16:
		return _PasswordOptionsMask_name_3
	case i == 32:
		return _PasswordOptionsMask_name_4
	case i == 64:
		return _PasswordOptionsMask_name_5
	case i == 128:
		return _PasswordOptionsMask_name_6
	case i == 256:
		return _PasswordOptionsMask_name_7
	default:
		return "PasswordOptionsMask(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UserConfigurationMaskNone-0]
	_ = x[UserConfigurationMaskNoDelete-1]
	_ = x[UserConfigurationMaskDisabled-2]
	_ = x[UserConfigurationMaskNoChangeByUser-4]
	_ = x[UserConfigurationMaskMustChangePassword-8]
}

const (
	_UserConfigurationMask_name_0 = "UserConfigurationMaskNoneUserConfigurationMaskNoDeleteUserConfigurationMaskDisabled"
	_UserConfigurationMask_name_1 = "UserConfigurationMaskNoChangeByUser"
	_UserConfigurationMask_name_2 = "UserConfigurationMaskMustChangePassword"
)

var (
	_UserConfigurationMask_index_0 = [...]uint8{0, 25, 54, 83}
)

func (i UserConfigurationMask) String() string {
	switch {
	case i <= 2:
		return _UserConfigurationMask_name_0[_UserConfigurationMask_index_0[i]:_UserConfigurationMask_index_0[i+1]]
	case i == 4:
		return _UserConfigurationMask_name_1
	case i == 8:
		return _UserConfigurationMask_name_2
	default:
		return "UserConfigurationMask(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DuplexFull-0]
	_ = x[DuplexHalf-1]
	_ = x[DuplexUnknown-2]
}

const _Duplex_name = "DuplexFullDuplexHalfDuplexUnknown"

var _Duplex_index = [...]uint8{0, 10, 20, 33}

func (i Duplex) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Duplex_index)-1 {
		return "Duplex(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Duplex_name[_Duplex_index[idx]:_Duplex_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InterfaceAdminStatusUp-0]
	_ = x[InterfaceAdminStatusDown-1]
	_ = x[InterfaceAdminStatusTesting-2]
}

const _InterfaceAdminStatus_name = "InterfaceAdminStatusUpInterfaceAdminStatusDownInterfaceAdminStatusTesting"

var _InterfaceAdminStatus_index = [...]uint8{0, 22, 46, 73}

func (i InterfaceAdminStatus) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_InterfaceAdminStatus_index)-1 {
		return "InterfaceAdminStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _InterfaceAdminStatus_name[_InterfaceAdminStatus_index[idx]:_InterfaceAdminStatus_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InterfaceOperStatusUp-0]
	_ = x[InterfaceOperStatusDown-1]
	_ = x[InterfaceOperStatusTesting-2]
	_ = x[InterfaceOperStatusUnknown-3]
	_ = x[InterfaceOperStatusDormant-4]
	_ = x[InterfaceOperStatusNotPresent-5]
	_ = x[InterfaceOperStatusLowerLayerDown-6]
}

const _InterfaceOperStatus_name = "InterfaceOperStatusUpInterfaceOperStatusDownInterfaceOperStatusTestingInterfaceOperStatusUnknownInterfaceOperStatusDormantInterfaceOperStatusNotPresentInterfaceOperStatusLowerLayerDown"

var _InterfaceOperStatus_index = [...]uint8{0, 21, 44, 70, 96, 122, 151, 184}

func (i InterfaceOperStatus) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_InterfaceOperStatus_index)-1 {
		return "InterfaceOperStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _InterfaceOperStatus_name[_InterfaceOperStatus_index[idx]:_InterfaceOperStatus_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NegotiationStatusInProgress-0]
	_ = x[NegotiationStatusComplete-1]
	_ = x[NegotiationStatusFailed-2]
	_ = x[NegotiationStatusUnknown-3]
	_ = x[NegotiationStatusNoNegotiation-4]
}

const _NegotiationStatus_name = "NegotiationStatusInProgressNegotiationStatusCompleteNegotiationStatusFailedNegotiationStatusUnknownNegotiationStatusNoNegotiation"

var _NegotiationStatus_index = [...]uint8{0, 27, 52, 75, 99, 129}

func (i NegotiationStatus) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_NegotiationStatus_index)-1 {
		return "NegotiationStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NegotiationStatus_name[_NegotiationStatus_index[idx]:_NegotiationStatus_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TsnFailureCodeNoFailure-0]
	_ = x[TsnFailureCodeInsufficientBandwidth-1]
	_ = x[TsnFailureCodeInsufficientResources-2]
	_ = x[TsnFailureCodeInsufficientTrafficClassBandwidth-3]
	_ = x[TsnFailureCodeStreamIDInUse-4]
	_ = x[TsnFailureCodeStreamDestinationAddressInUse-5]
	_ = x[TsnFailureCodeStreamPreemptedByHigherRank-6]
	_ = x[TsnFailureCodeLatencyHasChanged-7]
	_ = x[TsnFailureCodeEgressPortNotAvbCapable-8]
	_ = x[TsnFailureCodeUseDifferentDestinationAddress-9]
	_ = x[TsnFailureCodeOutOfMsrpResources-10]
	_ = x[TsnFailureCodeOutOfMmrpResources-11]
	_ = x[TsnFailureCodeCannotStoreDestinationAddress-12]
	_ = x[TsnFailureCodePriorityIsNotAnSrcClass-13]
	_ = x[TsnFailureCodeMaxFrameSizeTooLarge-14]
	_ = x[TsnFailureCodeMaxFanInPortsLimitReached-15]
	_ = x[TsnFailureCodeFirstValueChangedForStreamID-16]
	_ = x[TsnFailureCodeVlanBlockedOnEgress-17]
	_ = x[TsnFailureCodeVlanTaggingDisabledOnEgress-18]
	_ = x[TsnFailureCodeSrClassPriorityMismatch-19]
	_ = x[TsnFailureCodeFeatureNotPropagated-20]
	_ = x[TsnFailureCodeMaxLatencyExceeded-21]
	_ = x[TsnFailureCodeBridgeDoesNotProvideNetworkID-22]
	_ = x[TsnFailureCodeStreamTransformNotSupported-23]
	_ = x[TsnFailureCodeStreamIDTypeNotSupported-24]
	_ = x[TsnFailureCodeFeatureNotSupported-25]
}

const _TsnFailureCode_name = "TsnFailureCodeNoFailureTsnFailureCodeInsufficientBandwidthTsnFailureCodeInsufficientResourcesTsnFailureCodeInsufficientTrafficClassBandwidthTsnFailureCodeStreamIDInUseTsnFailureCodeStreamDestinationAddressInUseTsnFailureCodeStreamPreemptedByHigherRankTsnFailureCodeLatencyHasChangedTsnFailureCodeEgressPortNotAvbCapableTsnFailureCodeUseDifferentDestinationAddressTsnFailureCodeOutOfMsrpResourcesTsnFailureCodeOutOfMmrpResourcesTsnFailureCodeCannotStoreDestinationAddressTsnFailureCodePriorityIsNotAnSrcClassTsnFailureCodeMaxFrameSizeTooLargeTsnFailureCodeMaxFanInPortsLimitReachedTsnFailureCodeFirstValueChangedForStreamIDTsnFailureCodeVlanBlockedOnEgressTsnFailureCodeVlanTaggingDisabledOnEgressTsnFailureCodeSrClassPriorityMismatchTsnFailureCodeFeatureNotPropagatedTsnFailureCodeMaxLatencyExceededTsnFailureCodeBridgeDoesNotProvideNetworkIDTsnFailureCodeStreamTransformNotSupportedTsnFailureCodeStreamIDTypeNotSupportedTsnFailureCodeFeatureNotSupported"

var _TsnFailureCode_index = [...]uint16{0, 23, 58, 93, 140, 167, 210, 251, 282, 319, 363, 395, 427, 470, 507, 541, 580, 622, 655, 696, 733, 767, 799, 842, 883, 921, 954}

func (i TsnFailureCode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TsnFailureCode_index)-1 {
		return "TsnFailureCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TsnFailureCode_name[_TsnFailureCode_index[idx]:_TsnFailureCode_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TsnStreamStateDisabled-0]
	_ = x[TsnStreamStateConfiguring-1]
	_ = x[TsnStreamStateReady-2]
	_ = x[TsnStreamStateOperational-3]
	_ = x[TsnStreamStateError-4]
}

const _TsnStreamState_name = "TsnStreamStateDisabledTsnStreamStateConfiguringTsnStreamStateReadyTsnStreamStateOperationalTsnStreamStateError"

var _TsnStreamState_index = [...]uint8{0, 22, 47, 66, 91, 110}

func (i TsnStreamState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TsnStreamState_index)-1 {
		return "TsnStreamState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TsnStreamState_name[_TsnStreamState_index[idx]:_TsnStreamState_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TsnTalkerStatusNone-0]
	_ = x[TsnTalkerStatusReady-1]
	_ = x[TsnTalkerStatusFailed-2]
}

const _TsnTalkerStatus_name = "TsnTalkerStatusNoneTsnTalkerStatusReadyTsnTalkerStatusFailed"

var _TsnTalkerStatus_index = [...]uint8{0, 19, 39, 60}

func (i TsnTalkerStatus) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TsnTalkerStatus_index)-1 {
		return "TsnTalkerStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TsnTalkerStatus_name[_TsnTalkerStatus_index[idx]:_TsnTalkerStatus_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TsnListenerStatusNone-0]
	_ = x[TsnListenerStatusReady-1]
	_ = x[TsnListenerStatusPartialFailed-2]
	_ = x[TsnListenerStatusFailed-3]
}

const _TsnListenerStatus_name = "TsnListenerStatusNoneTsnListenerStatusReadyTsnListenerStatusPartialFailedTsnListenerStatusFailed"

var _TsnListenerStatus_index = [...]uint8{0, 21, 43, 73, 96}

func (i TsnListenerStatus) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TsnListenerStatus_index)-1 {
		return "TsnListenerStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TsnListenerStatus_name[_TsnListenerStatus_index[idx]:_TsnListenerStatus_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ChassisIDSubtypeChassisComponent-1]
	_ = x[ChassisIDSubtypeInterfaceAlias-2]
	_ = x[ChassisIDSubtypePortComponent-3]
	_ = x[ChassisIDSubtypeMacAddress-4]
	_ = x[ChassisIDSubtypeNetworkAddress-5]
	_ = x[ChassisIDSubtypeInterfaceName-6]
	_ = x[ChassisIDSubtypeLocal-7]
}

const _ChassisIDSubtype_name = "ChassisIDSubtypeChassisComponentChassisIDSubtypeInterfaceAliasChassisIDSubtypePortComponentChassisIDSubtypeMacAddressChassisIDSubtypeNetworkAddressChassisIDSubtypeInterfaceNameChassisIDSubtypeLocal"

var _ChassisIDSubtype_index = [...]uint8{0, 32, 62, 91, 117, 147, 176, 197}

func (i ChassisIDSubtype) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_ChassisIDSubtype_index)-1 {
		return "ChassisIDSubtype(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ChassisIDSubtype_name[_ChassisIDSubtype_index[idx]:_ChassisIDSubtype_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PortIDSubtypeInterfaceAlias-1]
	_ = x[PortIDSubtypePortComponent-2]
	_ = x[PortIDSubtypeMacAddress-3]
	_ = x[PortIDSubtypeNetworkAddress-4]
	_ = x[PortIDSubtypeInterfaceName-5]
	_ = x[PortIDSubtypeAgentCircuitID-6]
	_ = x[PortIDSubtypeLocal-7]
}

const _PortIDSubtype_name = "PortIDSubtypeInterfaceAliasPortIDSubtypePortComponentPortIDSubtypeMacAddressPortIDSubtypeNetworkAddressPortIDSubtypeInterfaceNamePortIDSubtypeAgentCircuitIDPortIDSubtypeLocal"

var _PortIDSubtype_index = [...]uint8{0, 27, 53, 76, 103, 129, 156, 174}

func (i PortIDSubtype) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_PortIDSubtype_index)-1 {
		return "PortIDSubtype(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PortIDSubtype_name[_PortIDSubtype_index[idx]:_PortIDSubtype_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ManAddrIfSubtypeNone-0]
	_ = x[ManAddrIfSubtypeUnknown-1]
	_ = x[ManAddrIfSubtypePortRef-2]
	_ = x[ManAddrIfSubtypeSystemPortNumber-3]
}

const _ManAddrIfSubtype_name = "ManAddrIfSubtypeNoneManAddrIfSubtypeUnknownManAddrIfSubtypePortRefManAddrIfSubtypeSystemPortNumber"

var _ManAddrIfSubtype_index = [...]uint8{0, 20, 43, 66, 98}

func (i ManAddrIfSubtype) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ManAddrIfSubtype_index)-1 {
		return "ManAddrIfSubtype(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ManAddrIfSubtype_name[_ManAddrIfSubtype_index[idx]:_ManAddrIfSubtype_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LldpSystemCapabilitiesMapNone-0]
	_ = x[LldpSystemCapabilitiesMapOther-1]
	_ = x[LldpSystemCapabilitiesMapRepeater-2]
	_ = x[LldpSystemCapabilitiesMapBridge-4]
	_ = x[LldpSystemCapabilitiesMapWlanAccessPoint-8]
	_ = x[LldpSystemCapabilitiesMapRouter-16]
	_ = x[LldpSystemCapabilitiesMapTelephone-32]
	_ = x[LldpSystemCapabilitiesMapDocsisCableDevice-64]
	_ = x[LldpSystemCapabilitiesMapStationOnly-128]
	_ = x[LldpSystemCapabilitiesMapCvlanComponent-256]
	_ = x[LldpSystemCapabilitiesMapSvlanComponent-512]
	_ = x[LldpSystemCapabilitiesMapTwoPortMacRelay-1024]
}

const (
	_LldpSystemCapabilitiesMap_name_0 = "LldpSystemCapabilitiesMapNoneLldpSystemCapabilitiesMapOtherLldpSystemCapabilitiesMapRepeater"
	_LldpSystemCapabilitiesMap_name_1 = "LldpSystemCapabilitiesMapBridge"
	_LldpSystemCapabilitiesMap_name_2 = "LldpSystemCapabilitiesMapWlanAccessPoint"
	_LldpSystemCapabilitiesMap_name_3 = "LldpSystemCapabilitiesMapRouter"
	_LldpSystemCapabilitiesMap_name_4 = "LldpSystemCapabilitiesMapTelephone"
	_LldpSystemCapabilitiesMap_name_5 = "LldpSystemCapabilitiesMapDocsisCableDevice"
	_LldpSystemCapabilitiesMap_name_6 = "LldpSystemCapabilitiesMapStationOnly"
	_LldpSystemCapabilitiesMap_name_7 = "LldpSystemCapabilitiesMapCvlanComponent"
	_LldpSystemCapabilitiesMap_name_8 = "LldpSystemCapabilitiesMapSvlanComponent"
	_LldpSystemCapabilitiesMap_name_9 = "LldpSystemCapabilitiesMapTwoPortMacRelay"
)

var (
	_LldpSystemCapabilitiesMap_index_0 = [...]uint8{0, 29, 59, 92}
)

func (i LldpSystemCapabilitiesMap) String() string {
	switch {
	case i <= 2:
		return _LldpSystemCapabilitiesMap_name_0[_LldpSystemCapabilitiesMap_index_0[i]:_LldpSystemCapabilitiesMap_index_0[i+1]]
	case i == 4:
		return _LldpSystemCapabilitiesMap_name_1
	case i == 8:
		return _LldpSystemCapabilitiesMap_name_2
	case i == 16:
		return _LldpSystemCapabilitiesMap_name_3
	case i == 32:
		return _LldpSystemCapabilitiesMap_name_4
	case i == 64:
		return _LldpSystemCapabilitiesMap_name_5
	case i == 128:
		return _LldpSystemCapabilitiesMap_name_6
	case i == 256:
		return _LldpSystemCapabilitiesMap_name_7
	case i == 512:
		return _LldpSystemCapabilitiesMap_name_8
	case i == 1024:
		return _LldpSystemCapabilitiesMap_name_9
	default:
		return "LldpSystemCapabilitiesMap(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LogRecordMaskNone-0]
	_ = x[LogRecordMaskEventType-1]
	_ = x[LogRecordMaskSourceNode-2]
	_ = x[LogRecordMaskSourceName-4]
	_ = x[LogRecordMaskTraceContext-8]
	_ = x[LogRecordMaskAdditionalData-16]
}

const (
	_LogRecordMask_name_0 = "LogRecordMaskNoneLogRecordMaskEventTypeLogRecordMaskSourceNode"
	_LogRecordMask_name_1 = "LogRecordMaskSourceName"
	_LogRecordMask_name_2 = "LogRecordMaskTraceContext"
	_LogRecordMask_name_3 = "LogRecordMaskAdditionalData"
)

var (
	_LogRecordMask_index_0 = [...]uint8{0, 17, 39, 62}
)

func (i LogRecordMask) String() string {
	switch {
	case i <= 2:
		return _LogRecordMask_name_0[_LogRecordMask_index_0[i]:_LogRecordMask_index_0[i+1]]
	case i == 4:
		return _LogRecordMask_name_1
	case i == 8:
		return _LogRecordMask_name_2
	case i == 16:
		return _LogRecordMask_name_3
	default:
		return "LogRecordMask(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IDTypeNumeric-0]
	_ = x[IDTypeString-1]
	_ = x[IDTypeGUID-2]
	_ = x[IDTypeOpaque-3]
}

const _IDType_name = "IDTypeNumericIDTypeStringIDTypeGUIDIDTypeOpaque"

var _IDType_index = [...]uint8{0, 13, 25, 35, 47}

func (i IDType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_IDType_index)-1 {
		return "IDType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IDType_name[_IDType_index[idx]:_IDType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NodeClassAll-255]
	_ = x[NodeClassUnspecified-0]
	_ = x[NodeClassObject-1]
	_ = x[NodeClassVariable-2]
	_ = x[NodeClassMethod-4]
	_ = x[NodeClassObjectType-8]
	_ = x[NodeClassVariableType-16]
	_ = x[NodeClassReferenceType-32]
	_ = x[NodeClassDataType-64]
	_ = x[NodeClassView-128]
}

const (
	_NodeClass_name_0 = "NodeClassUnspecifiedNodeClassObjectNodeClassVariable"
	_NodeClass_name_1 = "NodeClassMethod"
	_NodeClass_name_2 = "NodeClassObjectType"
	_NodeClass_name_3 = "NodeClassVariableType"
	_NodeClass_name_4 = "NodeClassReferenceType"
	_NodeClass_name_5 = "NodeClassDataType"
	_NodeClass_name_6 = "NodeClassView"
	_NodeClass_name_7 = "NodeClassAll"
)

var (
	_NodeClass_index_0 = [...]uint8{0, 20, 35, 52}
)

func (i NodeClass) String() string {
	switch {
	case i <= 2:
		return _NodeClass_name_0[_NodeClass_index_0[i]:_NodeClass_index_0[i+1]]
	case i == 4:
		return _NodeClass_name_1
	case i == 8:
		return _NodeClass_name_2
	case i == 16:
		return _NodeClass_name_3
	case i == 32:
		return _NodeClass_name_4
	case i == 64:
		return _NodeClass_name_5
	case i == 128:
		return _NodeClass_name_6
	case i == 255:
		return _NodeClass_name_7
	default:
		return "NodeClass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PermissionTypeNone-0]
	_ = x[PermissionTypeBrowse-1]
	_ = x[PermissionTypeReadRolePermissions-2]
	_ = x[PermissionTypeWriteAttribute-4]
	_ = x[PermissionTypeWriteRolePermissions-8]
	_ = x[PermissionTypeWriteHistorizing-16]
	_ = x[PermissionTypeRead-32]
	_ = x[PermissionTypeWrite-64]
	_ = x[PermissionTypeReadHistory-128]
	_ = x[PermissionTypeInsertHistory-256]
	_ = x[PermissionTypeModifyHistory-512]
	_ = x[PermissionTypeDeleteHistory-1024]
	_ = x[PermissionTypeReceiveEvents-2048]
	_ = x[PermissionTypeCall-4096]
	_ = x[PermissionTypeAddReference-8192]
	_ = x[PermissionTypeRemoveReference-16384]
	_ = x[PermissionTypeDeleteNode-32768]
	_ = x[PermissionTypeAddNode-65536]
}

const _PermissionType_name = "PermissionTypeNonePermissionTypeBrowsePermissionTypeReadRolePermissionsPermissionTypeWriteAttributePermissionTypeWriteRolePermissionsPermissionTypeWriteHistorizingPermissionTypeReadPermissionTypeWritePermissionTypeReadHistoryPermissionTypeInsertHistoryPermissionTypeModifyHistoryPermissionTypeDeleteHistoryPermissionTypeReceiveEventsPermissionTypeCallPermissionTypeAddReferencePermissionTypeRemoveReferencePermissionTypeDeleteNodePermissionTypeAddNode"

var _PermissionType_map = map[PermissionType]string{
	0:     _PermissionType_name[0:18],
	1:     _PermissionType_name[18:38],
	2:     _PermissionType_name[38:71],
	4:     _PermissionType_name[71:99],
	8:     _PermissionType_name[99:133],
	16:    _PermissionType_name[133:163],
	32:    _PermissionType_name[163:181],
	64:    _PermissionType_name[181:200],
	128:   _PermissionType_name[200:225],
	256:   _PermissionType_name[225:252],
	512:   _PermissionType_name[252:279],
	1024:  _PermissionType_name[279:306],
	2048:  _PermissionType_name[306:333],
	4096:  _PermissionType_name[333:351],
	8192:  _PermissionType_name[351:377],
	16384: _PermissionType_name[377:406],
	32768: _PermissionType_name[406:430],
	65536: _PermissionType_name[430:451],
}

func (i PermissionType) String() string {
	if str, ok := _PermissionType_map[i]; ok {
		return str
	}
	return "PermissionType(" + strconv.FormatInt(int64(i), 10) + ")"
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AccessLevelTypeNone-0]
	_ = x[AccessLevelTypeCurrentRead-1]
	_ = x[AccessLevelTypeCurrentWrite-2]
	_ = x[AccessLevelTypeHistoryRead-4]
	_ = x[AccessLevelTypeHistoryWrite-8]
	_ = x[AccessLevelTypeSemanticChange-16]
	_ = x[AccessLevelTypeStatusWrite-32]
	_ = x[AccessLevelTypeTimestampWrite-64]
}

const (
	_AccessLevelType_name_0 = "AccessLevelTypeNoneAccessLevelTypeCurrentReadAccessLevelTypeCurrentWrite"
	_AccessLevelType_name_1 = "AccessLevelTypeHistoryRead"
	_AccessLevelType_name_2 = "AccessLevelTypeHistoryWrite"
	_AccessLevelType_name_3 = "AccessLevelTypeSemanticChange"
	_AccessLevelType_name_4 = "AccessLevelTypeStatusWrite"
	_AccessLevelType_name_5 = "AccessLevelTypeTimestampWrite"
)

var (
	_AccessLevelType_index_0 = [...]uint8{0, 19, 45, 72}
)

func (i AccessLevelType) String() string {
	switch {
	case i <= 2:
		return _AccessLevelType_name_0[_AccessLevelType_index_0[i]:_AccessLevelType_index_0[i+1]]
	case i == 4:
		return _AccessLevelType_name_1
	case i == 8:
		return _AccessLevelType_name_2
	case i == 16:
		return _AccessLevelType_name_3
	case i == 32:
		return _AccessLevelType_name_4
	case i == 64:
		return _AccessLevelType_name_5
	default:
		return "AccessLevelType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AccessLevelExTypeNone-0]
	_ = x[AccessLevelExTypeCurrentRead-1]
	_ = x[AccessLevelExTypeCurrentWrite-2]
	_ = x[AccessLevelExTypeHistoryRead-4]
	_ = x[AccessLevelExTypeHistoryWrite-8]
	_ = x[AccessLevelExTypeSemanticChange-16]
	_ = x[AccessLevelExTypeStatusWrite-32]
	_ = x[AccessLevelExTypeTimestampWrite-64]
	_ = x[AccessLevelExTypeNonatomicRead-256]
	_ = x[AccessLevelExTypeNonatomicWrite-512]
	_ = x[AccessLevelExTypeWriteFullArrayOnly-1024]
	_ = x[AccessLevelExTypeNoSubDataTypes-2048]
	_ = x[AccessLevelExTypeNonVolatile-4096]
	_ = x[AccessLevelExTypeConstant-8192]
}

const _AccessLevelExType_name = "AccessLevelExTypeNoneAccessLevelExTypeCurrentReadAccessLevelExTypeCurrentWriteAccessLevelExTypeHistoryReadAccessLevelExTypeHistoryWriteAccessLevelExTypeSemanticChangeAccessLevelExTypeStatusWriteAccessLevelExTypeTimestampWriteAccessLevelExTypeNonatomicReadAccessLevelExTypeNonatomicWriteAccessLevelExTypeWriteFullArrayOnlyAccessLevelExTypeNoSubDataTypesAccessLevelExTypeNonVolatileAccessLevelExTypeConstant"

var _AccessLevelExType_map = map[AccessLevelExType]string{
	0:    _AccessLevelExType_name[0:21],
	1:    _AccessLevelExType_name[21:49],
	2:    _AccessLevelExType_name[49:78],
	4:    _AccessLevelExType_name[78:106],
	8:    _AccessLevelExType_name[106:135],
	16:   _AccessLevelExType_name[135:166],
	32:   _AccessLevelExType_name[166:194],
	64:   _AccessLevelExType_name[194:225],
	256:  _AccessLevelExType_name[225:255],
	512:  _AccessLevelExType_name[255:286],
	1024: _AccessLevelExType_name[286:321],
	2048: _AccessLevelExType_name[321:352],
	4096: _AccessLevelExType_name[352:380],
	8192: _AccessLevelExType_name[380:405],
}

func (i AccessLevelExType) String() string {
	if str, ok := _AccessLevelExType_map[i]; ok {
		return str
	}
	return "AccessLevelExType(" + strconv.FormatInt(int64(i), 10) + ")"
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventNotifierTypeNone-0]
	_ = x[EventNotifierTypeSubscribeToEvents-1]
	_ = x[EventNotifierTypeHistoryRead-4]
	_ = x[EventNotifierTypeHistoryWrite-8]
}

const (
	_EventNotifierType_name_0 = "EventNotifierTypeNoneEventNotifierTypeSubscribeToEvents"
	_EventNotifierType_name_1 = "EventNotifierTypeHistoryRead"
	_EventNotifierType_name_2 = "EventNotifierTypeHistoryWrite"
)

var (
	_EventNotifierType_index_0 = [...]uint8{0, 21, 55}
)

func (i EventNotifierType) String() string {
	switch {
	case i <= 1:
		return _EventNotifierType_name_0[_EventNotifierType_index_0[i]:_EventNotifierType_index_0[i+1]]
	case i == 4:
		return _EventNotifierType_name_1
	case i == 8:
		return _EventNotifierType_name_2
	default:
		return "EventNotifierType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AccessRestrictionTypeNone-0]
	_ = x[AccessRestrictionTypeSigningRequired-1]
	_ = x[AccessRestrictionTypeEncryptionRequired-2]
	_ = x[AccessRestrictionTypeSessionRequired-4]
	_ = x[AccessRestrictionTypeApplyRestrictionsToBrowse-8]
}

const (
	_AccessRestrictionType_name_0 = "AccessRestrictionTypeNoneAccessRestrictionTypeSigningRequiredAccessRestrictionTypeEncryptionRequired"
	_AccessRestrictionType_name_1 = "AccessRestrictionTypeSessionRequired"
	_AccessRestrictionType_name_2 = "AccessRestrictionTypeApplyRestrictionsToBrowse"
)

var (
	_AccessRestrictionType_index_0 = [...]uint8{0, 25, 61, 100}
)

func (i AccessRestrictionType) String() string {
	switch {
	case i <= 2:
		return _AccessRestrictionType_name_0[_AccessRestrictionType_index_0[i]:_AccessRestrictionType_index_0[i+1]]
	case i == 4:
		return _AccessRestrictionType_name_1
	case i == 8:
		return _AccessRestrictionType_name_2
	default:
		return "AccessRestrictionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StructureTypeStructure-0]
	_ = x[StructureTypeStructureWithOptionalFields-1]
	_ = x[StructureTypeUnion-2]
	_ = x[StructureTypeStructureWithSubtypedValues-3]
	_ = x[StructureTypeUnionWithSubtypedValues-4]
}

const _StructureType_name = "StructureTypeStructureStructureTypeStructureWithOptionalFieldsStructureTypeUnionStructureTypeStructureWithSubtypedValuesStructureTypeUnionWithSubtypedValues"

var _StructureType_index = [...]uint8{0, 22, 62, 80, 120, 156}

func (i StructureType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_StructureType_index)-1 {
		return "StructureType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StructureType_name[_StructureType_index[idx]:_StructureType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ApplicationTypeServer-0]
	_ = x[ApplicationTypeClient-1]
	_ = x[ApplicationTypeClientAndServer-2]
	_ = x[ApplicationTypeDiscoveryServer-3]
}

const _ApplicationType_name = "ApplicationTypeServerApplicationTypeClientApplicationTypeClientAndServerApplicationTypeDiscoveryServer"

var _ApplicationType_index = [...]uint8{0, 21, 42, 72, 102}

func (i ApplicationType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ApplicationType_index)-1 {
		return "ApplicationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ApplicationType_name[_ApplicationType_index[idx]:_ApplicationType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MessageSecurityModeInvalid-0]
	_ = x[MessageSecurityModeNone-1]
	_ = x[MessageSecurityModeSign-2]
	_ = x[MessageSecurityModeSignAndEncrypt-3]
}

const _MessageSecurityMode_name = "MessageSecurityModeInvalidMessageSecurityModeNoneMessageSecurityModeSignMessageSecurityModeSignAndEncrypt"

var _MessageSecurityMode_index = [...]uint8{0, 26, 49, 72, 105}

func (i MessageSecurityMode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_MessageSecurityMode_index)-1 {
		return "MessageSecurityMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MessageSecurityMode_name[_MessageSecurityMode_index[idx]:_MessageSecurityMode_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UserTokenTypeAnonymous-0]
	_ = x[UserTokenTypeUserName-1]
	_ = x[UserTokenTypeCertificate-2]
	_ = x[UserTokenTypeIssuedToken-3]
}

const _UserTokenType_name = "UserTokenTypeAnonymousUserTokenTypeUserNameUserTokenTypeCertificateUserTokenTypeIssuedToken"

var _UserTokenType_index = [...]uint8{0, 22, 43, 67, 91}

func (i UserTokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_UserTokenType_index)-1 {
		return "UserTokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UserTokenType_name[_UserTokenType_index[idx]:_UserTokenType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SecurityTokenRequestTypeIssue-0]
	_ = x[SecurityTokenRequestTypeRenew-1]
}

const _SecurityTokenRequestType_name = "SecurityTokenRequestTypeIssueSecurityTokenRequestTypeRenew"

var _SecurityTokenRequestType_index = [...]uint8{0, 29, 58}

func (i SecurityTokenRequestType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_SecurityTokenRequestType_index)-1 {
		return "SecurityTokenRequestType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SecurityTokenRequestType_name[_SecurityTokenRequestType_index[idx]:_SecurityTokenRequestType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NodeAttributesMaskNone-0]
	_ = x[NodeAttributesMaskAccessLevel-1]
	_ = x[NodeAttributesMaskArrayDimensions-2]
	_ = x[NodeAttributesMaskBrowseName-4]
	_ = x[NodeAttributesMaskContainsNoLoops-8]
	_ = x[NodeAttributesMaskDataType-16]
	_ = x[NodeAttributesMaskDescription-32]
	_ = x[NodeAttributesMaskDisplayName-64]
	_ = x[NodeAttributesMaskEventNotifier-128]
	_ = x[NodeAttributesMaskExecutable-256]
	_ = x[NodeAttributesMaskHistorizing-512]
	_ = x[NodeAttributesMaskInverseName-1024]
	_ = x[NodeAttributesMaskIsAbstract-2048]
	_ = x[NodeAttributesMaskMinimumSamplingInterval-4096]
	_ = x[NodeAttributesMaskNodeClass-8192]
	_ = x[NodeAttributesMaskNodeID-16384]
	_ = x[NodeAttributesMaskSymmetric-32768]
	_ = x[NodeAttributesMaskUserAccessLevel-65536]
	_ = x[NodeAttributesMaskUserExecutable-131072]
	_ = x[NodeAttributesMaskUserWriteMask-262144]
	_ = x[NodeAttributesMaskValueRank-524288]
	_ = x[NodeAttributesMaskWriteMask-1048576]
	_ = x[NodeAttributesMaskValue-2097152]
	_ = x[NodeAttributesMaskDataTypeDefinition-4194304]
	_ = x[NodeAttributesMaskRolePermissions-8388608]
	_ = x[NodeAttributesMaskAccessRestrictions-16777216]
	_ = x[NodeAttributesMaskAll-33554431]
	_ = x[NodeAttributesMaskBaseNode-26501220]
	_ = x[NodeAttributesMaskObject-26501348]
	_ = x[NodeAttributesMaskObjectType-26503268]
	_ = x[NodeAttributesMaskVariable-26571383]
	_ = x[NodeAttributesMaskVariableType-28600438]
	_ = x[NodeAttributesMaskMethod-26632548]
	_ = x[NodeAttributesMaskReferenceType-26537060]
	_ = x[NodeAttributesMaskView-26501356]
}

const _NodeAttributesMask_name = "NodeAttributesMaskNoneNodeAttributesMaskAccessLevelNodeAttributesMaskArrayDimensionsNodeAttributesMaskBrowseNameNodeAttributesMaskContainsNoLoopsNodeAttributesMaskDataTypeNodeAttributesMaskDescriptionNodeAttributesMaskDisplayNameNodeAttributesMaskEventNotifierNodeAttributesMaskExecutableNodeAttributesMaskHistorizingNodeAttributesMaskInverseNameNodeAttributesMaskIsAbstractNodeAttributesMaskMinimumSamplingIntervalNodeAttributesMaskNodeClassNodeAttributesMaskNodeIDNodeAttributesMaskSymmetricNodeAttributesMaskUserAccessLevelNodeAttributesMaskUserExecutableNodeAttributesMaskUserWriteMaskNodeAttributesMaskValueRankNodeAttributesMaskWriteMaskNodeAttributesMaskValueNodeAttributesMaskDataTypeDefinitionNodeAttributesMaskRolePermissionsNodeAttributesMaskAccessRestrictionsNodeAttributesMaskBaseNodeNodeAttributesMaskObjectNodeAttributesMaskViewNodeAttributesMaskObjectTypeNodeAttributesMaskReferenceTypeNodeAttributesMaskVariableNodeAttributesMaskMethodNodeAttributesMaskVariableTypeNodeAttributesMaskAll"

var _NodeAttributesMask_map = map[NodeAttributesMask]string{
	0:        _NodeAttributesMask_name[0:22],
	1:        _NodeAttributesMask_name[22:51],
	2:        _NodeAttributesMask_name[51:84],
	4:        _NodeAttributesMask_name[84:112],
	8:        _NodeAttributesMask_name[112:145],
	16:       _NodeAttributesMask_name[145:171],
	32:       _NodeAttributesMask_name[171:200],
	64:       _NodeAttributesMask_name[200:229],
	128:      _NodeAttributesMask_name[229:260],
	256:      _NodeAttributesMask_name[260:288],
	512:      _NodeAttributesMask_name[288:317],
	1024:     _NodeAttributesMask_name[317:346],
	2048:     _NodeAttributesMask_name[346:374],
	4096:     _NodeAttributesMask_name[374:415],
	8192:     _NodeAttributesMask_name[415:442],
	16384:    _NodeAttributesMask_name[442:466],
	32768:    _NodeAttributesMask_name[466:493],
	65536:    _NodeAttributesMask_name[493:526],
	131072:   _NodeAttributesMask_name[526:558],
	262144:   _NodeAttributesMask_name[558:589],
	524288:   _NodeAttributesMask_name[589:616],
	1048576:  _NodeAttributesMask_name[616:643],
	2097152:  _NodeAttributesMask_name[643:666],
	4194304:  _NodeAttributesMask_name[666:702],
	8388608:  _NodeAttributesMask_name[702:735],
	16777216: _NodeAttributesMask_name[735:771],
	26501220: _NodeAttributesMask_name[771:797],
	26501348: _NodeAttributesMask_name[797:821],
	26501356: _NodeAttributesMask_name[821:843],
	26503268: _NodeAttributesMask_name[843:871],
	26537060: _NodeAttributesMask_name[871:902],
	26571383: _NodeAttributesMask_name[902:928],
	26632548: _NodeAttributesMask_name[928:952],
	28600438: _NodeAttributesMask_name[952:982],
	33554431: _NodeAttributesMask_name[982:1003],
}

func (i NodeAttributesMask) String() string {
	if str, ok := _NodeAttributesMask_map[i]; ok {
		return str
	}
	return "NodeAttributesMask(" + strconv.FormatInt(int64(i), 10) + ")"
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AttributeWriteMaskNone-0]
	_ = x[AttributeWriteMaskAccessLevel-1]
	_ = x[AttributeWriteMaskArrayDimensions-2]
	_ = x[AttributeWriteMaskBrowseName-4]
	_ = x[AttributeWriteMaskContainsNoLoops-8]
	_ = x[AttributeWriteMaskDataType-16]
	_ = x[AttributeWriteMaskDescription-32]
	_ = x[AttributeWriteMaskDisplayName-64]
	_ = x[AttributeWriteMaskEventNotifier-128]
	_ = x[AttributeWriteMaskExecutable-256]
	_ = x[AttributeWriteMaskHistorizing-512]
	_ = x[AttributeWriteMaskInverseName-1024]
	_ = x[AttributeWriteMaskIsAbstract-2048]
	_ = x[AttributeWriteMaskMinimumSamplingInterval-4096]
	_ = x[AttributeWriteMaskNodeClass-8192]
	_ = x[AttributeWriteMaskNodeID-16384]
	_ = x[AttributeWriteMaskSymmetric-32768]
	_ = x[AttributeWriteMaskUserAccessLevel-65536]
	_ = x[AttributeWriteMaskUserExecutable-131072]
	_ = x[AttributeWriteMaskUserWriteMask-262144]
	_ = x[AttributeWriteMaskValueRank-524288]
	_ = x[AttributeWriteMaskWriteMask-1048576]
	_ = x[AttributeWriteMaskValueForVariableType-2097152]
	_ = x[AttributeWriteMaskDataTypeDefinition-4194304]
	_ = x[AttributeWriteMaskRolePermissions-8388608]
	_ = x[AttributeWriteMaskAccessRestrictions-16777216]
	_ = x[AttributeWriteMaskAccessLevelEx-33554432]
}

const _AttributeWriteMask_name = "AttributeWriteMaskNoneAttributeWriteMaskAccessLevelAttributeWriteMaskArrayDimensionsAttributeWriteMaskBrowseNameAttributeWriteMaskContainsNoLoopsAttributeWriteMaskDataTypeAttributeWriteMaskDescriptionAttributeWriteMaskDisplayNameAttributeWriteMaskEventNotifierAttributeWriteMaskExecutableAttributeWriteMaskHistorizingAttributeWriteMaskInverseNameAttributeWriteMaskIsAbstractAttributeWriteMaskMinimumSamplingIntervalAttributeWriteMaskNodeClassAttributeWriteMaskNodeIDAttributeWriteMaskSymmetricAttributeWriteMaskUserAccessLevelAttributeWriteMaskUserExecutableAttributeWriteMaskUserWriteMaskAttributeWriteMaskValueRankAttributeWriteMaskWriteMaskAttributeWriteMaskValueForVariableTypeAttributeWriteMaskDataTypeDefinitionAttributeWriteMaskRolePermissionsAttributeWriteMaskAccessRestrictionsAttributeWriteMaskAccessLevelEx"

var _AttributeWriteMask_map = map[AttributeWriteMask]string{
	0:        _AttributeWriteMask_name[0:22],
	1:        _AttributeWriteMask_name[22:51],
	2:        _AttributeWriteMask_name[51:84],
	4:        _AttributeWriteMask_name[84:112],
	8:        _AttributeWriteMask_name[112:145],
	16:       _AttributeWriteMask_name[145:171],
	32:       _AttributeWriteMask_name[171:200],
	64:       _AttributeWriteMask_name[200:229],
	128:      _AttributeWriteMask_name[229:260],
	256:      _AttributeWriteMask_name[260:288],
	512:      _AttributeWriteMask_name[288:317],
	1024:     _AttributeWriteMask_name[317:346],
	2048:     _AttributeWriteMask_name[346:374],
	4096:     _AttributeWriteMask_name[374:415],
	8192:     _AttributeWriteMask_name[415:442],
	16384:    _AttributeWriteMask_name[442:466],
	32768:    _AttributeWriteMask_name[466:493],
	65536:    _AttributeWriteMask_name[493:526],
	131072:   _AttributeWriteMask_name[526:558],
	262144:   _AttributeWriteMask_name[558:589],
	524288:   _AttributeWriteMask_name[589:616],
	1048576:  _AttributeWriteMask_name[616:643],
	2097152:  _AttributeWriteMask_name[643:681],
	4194304:  _AttributeWriteMask_name[681:717],
	8388608:  _AttributeWriteMask_name[717:750],
	16777216: _AttributeWriteMask_name[750:786],
	33554432: _AttributeWriteMask_name[786:817],
}

func (i AttributeWriteMask) String() string {
	if str, ok := _AttributeWriteMask_map[i]; ok {
		return str
	}
	return "AttributeWriteMask(" + strconv.FormatInt(int64(i), 10) + ")"
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BrowseDirectionForward-0]
	_ = x[BrowseDirectionInverse-1]
	_ = x[BrowseDirectionBoth-2]
	_ = x[BrowseDirectionInvalid-3]
}

const _BrowseDirection_name = "BrowseDirectionForwardBrowseDirectionInverseBrowseDirectionBothBrowseDirectionInvalid"

var _BrowseDirection_index = [...]uint8{0, 22, 44, 63, 85}

func (i BrowseDirection) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_BrowseDirection_index)-1 {
		return "BrowseDirection(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BrowseDirection_name[_BrowseDirection_index[idx]:_BrowseDirection_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BrowseResultMaskNone-0]
	_ = x[BrowseResultMaskReferenceTypeID-1]
	_ = x[BrowseResultMaskIsForward-2]
	_ = x[BrowseResultMaskNodeClass-4]
	_ = x[BrowseResultMaskBrowseName-8]
	_ = x[BrowseResultMaskDisplayName-16]
	_ = x[BrowseResultMaskTypeDefinition-32]
	_ = x[BrowseResultMaskAll-63]
	_ = x[BrowseResultMaskReferenceTypeInfo-3]
	_ = x[BrowseResultMaskTargetInfo-60]
}

const (
	_BrowseResultMask_name_0 = "BrowseResultMaskNoneBrowseResultMaskReferenceTypeIDBrowseResultMaskIsForwardBrowseResultMaskReferenceTypeInfoBrowseResultMaskNodeClass"
	_BrowseResultMask_name_1 = "BrowseResultMaskBrowseName"
	_BrowseResultMask_name_2 = "BrowseResultMaskDisplayName"
	_BrowseResultMask_name_3 = "BrowseResultMaskTypeDefinition"
	_BrowseResultMask_name_4 = "BrowseResultMaskTargetInfo"
	_BrowseResultMask_name_5 = "BrowseResultMaskAll"
)

var (
	_BrowseResultMask_index_0 = [...]uint8{0, 20, 51, 76, 109, 134}
)

func (i BrowseResultMask) String() string {
	switch {
	case i <= 4:
		return _BrowseResultMask_name_0[_BrowseResultMask_index_0[i]:_BrowseResultMask_index_0[i+1]]
	case i == 8:
		return _BrowseResultMask_name_1
	case i == 16:
		return _BrowseResultMask_name_2
	case i == 32:
		return _BrowseResultMask_name_3
	case i == 60:
		return _BrowseResultMask_name_4
	case i == 63:
		return _BrowseResultMask_name_5
	default:
		return "BrowseResultMask(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FilterOperatorEquals-0]
	_ = x[FilterOperatorIsNull-1]
	_ = x[FilterOperatorGreaterThan-2]
	_ = x[FilterOperatorLessThan-3]
	_ = x[FilterOperatorGreaterThanOrEqual-4]
	_ = x[FilterOperatorLessThanOrEqual-5]
	_ = x[FilterOperatorLike-6]
	_ = x[FilterOperatorNot-7]
	_ = x[FilterOperatorBetween-8]
	_ = x[FilterOperatorInList-9]
	_ = x[FilterOperatorAnd-10]
	_ = x[FilterOperatorOr-11]
	_ = x[FilterOperatorCast-12]
	_ = x[FilterOperatorInView-13]
	_ = x[FilterOperatorOfType-14]
	_ = x[FilterOperatorRelatedTo-15]
	_ = x[FilterOperatorBitwiseAnd-16]
	_ = x[FilterOperatorBitwiseOr-17]
}

const _FilterOperator_name = "FilterOperatorEqualsFilterOperatorIsNullFilterOperatorGreaterThanFilterOperatorLessThanFilterOperatorGreaterThanOrEqualFilterOperatorLessThanOrEqualFilterOperatorLikeFilterOperatorNotFilterOperatorBetweenFilterOperatorInListFilterOperatorAndFilterOperatorOrFilterOperatorCastFilterOperatorInViewFilterOperatorOfTypeFilterOperatorRelatedToFilterOperatorBitwiseAndFilterOperatorBitwiseOr"

var _FilterOperator_index = [...]uint16{0, 20, 40, 65, 87, 119, 148, 166, 183, 204, 224, 241, 257, 275, 295, 315, 338, 362, 385}

func (i FilterOperator) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_FilterOperator_index)-1 {
		return "FilterOperator(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FilterOperator_name[_FilterOperator_index[idx]:_FilterOperator_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TimestampsToReturnSource-0]
	_ = x[TimestampsToReturnServer-1]
	_ = x[TimestampsToReturnBoth-2]
	_ = x[TimestampsToReturnNeither-3]
	_ = x[TimestampsToReturnInvalid-4]
}

const _TimestampsToReturn_name = "TimestampsToReturnSourceTimestampsToReturnServerTimestampsToReturnBothTimestampsToReturnNeitherTimestampsToReturnInvalid"

var _TimestampsToReturn_index = [...]uint8{0, 24, 48, 70, 95, 120}

func (i TimestampsToReturn) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TimestampsToReturn_index)-1 {
		return "TimestampsToReturn(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TimestampsToReturn_name[_TimestampsToReturn_index[idx]:_TimestampsToReturn_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SortOrderTypeAscending-0]
	_ = x[SortOrderTypeDescending-1]
}

const _SortOrderType_name = "SortOrderTypeAscendingSortOrderTypeDescending"

var _SortOrderType_index = [...]uint8{0, 22, 45}

func (i SortOrderType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_SortOrderType_index)-1 {
		return "SortOrderType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SortOrderType_name[_SortOrderType_index[idx]:_SortOrderType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HistoryUpdateTypeInsert-1]
	_ = x[HistoryUpdateTypeReplace-2]
	_ = x[HistoryUpdateTypeUpdate-3]
	_ = x[HistoryUpdateTypeDelete-4]
}

const _HistoryUpdateType_name = "HistoryUpdateTypeInsertHistoryUpdateTypeReplaceHistoryUpdateTypeUpdateHistoryUpdateTypeDelete"

var _HistoryUpdateType_index = [...]uint8{0, 23, 47, 70, 93}

func (i HistoryUpdateType) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_HistoryUpdateType_index)-1 {
		return "HistoryUpdateType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HistoryUpdateType_name[_HistoryUpdateType_index[idx]:_HistoryUpdateType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PerformUpdateTypeInsert-1]
	_ = x[PerformUpdateTypeReplace-2]
	_ = x[PerformUpdateTypeUpdate-3]
	_ = x[PerformUpdateTypeRemove-4]
}

const _PerformUpdateType_name = "PerformUpdateTypeInsertPerformUpdateTypeReplacePerformUpdateTypeUpdatePerformUpdateTypeRemove"

var _PerformUpdateType_index = [...]uint8{0, 23, 47, 70, 93}

func (i PerformUpdateType) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_PerformUpdateType_index)-1 {
		return "PerformUpdateType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PerformUpdateType_name[_PerformUpdateType_index[idx]:_PerformUpdateType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MonitoringModeDisabled-0]
	_ = x[MonitoringModeSampling-1]
	_ = x[MonitoringModeReporting-2]
}

const _MonitoringMode_name = "MonitoringModeDisabledMonitoringModeSamplingMonitoringModeReporting"

var _MonitoringMode_index = [...]uint8{0, 22, 44, 67}

func (i MonitoringMode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_MonitoringMode_index)-1 {
		return "MonitoringMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MonitoringMode_name[_MonitoringMode_index[idx]:_MonitoringMode_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DataChangeTriggerStatus-0]
	_ = x[DataChangeTriggerStatusValue-1]
	_ = x[DataChangeTriggerStatusValueTimestamp-2]
}

const _DataChangeTrigger_name = "DataChangeTriggerStatusDataChangeTriggerStatusValueDataChangeTriggerStatusValueTimestamp"

var _DataChangeTrigger_index = [...]uint8{0, 23, 51, 88}

func (i DataChangeTrigger) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_DataChangeTrigger_index)-1 {
		return "DataChangeTrigger(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataChangeTrigger_name[_DataChangeTrigger_index[idx]:_DataChangeTrigger_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DeadbandTypeNone-0]
	_ = x[DeadbandTypeAbsolute-1]
	_ = x[DeadbandTypePercent-2]
}

const _DeadbandType_name = "DeadbandTypeNoneDeadbandTypeAbsoluteDeadbandTypePercent"

var _DeadbandType_index = [...]uint8{0, 16, 36, 55}

func (i DeadbandType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_DeadbandType_index)-1 {
		return "DeadbandType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DeadbandType_name[_DeadbandType_index[idx]:_DeadbandType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RedundancySupportNone-0]
	_ = x[RedundancySupportCold-1]
	_ = x[RedundancySupportWarm-2]
	_ = x[RedundancySupportHot-3]
	_ = x[RedundancySupportTransparent-4]
	_ = x[RedundancySupportHotAndMirrored-5]
}

const _RedundancySupport_name = "RedundancySupportNoneRedundancySupportColdRedundancySupportWarmRedundancySupportHotRedundancySupportTransparentRedundancySupportHotAndMirrored"

var _RedundancySupport_index = [...]uint8{0, 21, 42, 63, 83, 111, 142}

func (i RedundancySupport) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RedundancySupport_index)-1 {
		return "RedundancySupport(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RedundancySupport_name[_RedundancySupport_index[idx]:_RedundancySupport_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ServerStateRunning-0]
	_ = x[ServerStateFailed-1]
	_ = x[ServerStateNoConfiguration-2]
	_ = x[ServerStateSuspended-3]
	_ = x[ServerStateShutdown-4]
	_ = x[ServerStateTest-5]
	_ = x[ServerStateCommunicationFault-6]
	_ = x[ServerStateUnknown-7]
}

const _ServerState_name = "ServerStateRunningServerStateFailedServerStateNoConfigurationServerStateSuspendedServerStateShutdownServerStateTestServerStateCommunicationFaultServerStateUnknown"

var _ServerState_index = [...]uint8{0, 18, 35, 61, 81, 100, 115, 144, 162}

func (i ServerState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ServerState_index)-1 {
		return "ServerState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ServerState_name[_ServerState_index[idx]:_ServerState_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ModelChangeStructureVerbMaskNodeAdded-1]
	_ = x[ModelChangeStructureVerbMaskNodeDeleted-2]
	_ = x[ModelChangeStructureVerbMaskReferenceAdded-4]
	_ = x[ModelChangeStructureVerbMaskReferenceDeleted-8]
	_ = x[ModelChangeStructureVerbMaskDataTypeChanged-16]
}

const (
	_ModelChangeStructureVerbMask_name_0 = "ModelChangeStructureVerbMaskNodeAddedModelChangeStructureVerbMaskNodeDeleted"
	_ModelChangeStructureVerbMask_name_1 = "ModelChangeStructureVerbMaskReferenceAdded"
	_ModelChangeStructureVerbMask_name_2 = "ModelChangeStructureVerbMaskReferenceDeleted"
	_ModelChangeStructureVerbMask_name_3 = "ModelChangeStructureVerbMaskDataTypeChanged"
)

var (
	_ModelChangeStructureVerbMask_index_0 = [...]uint8{0, 37, 76}
)

func (i ModelChangeStructureVerbMask) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _ModelChangeStructureVerbMask_name_0[_ModelChangeStructureVerbMask_index_0[i]:_ModelChangeStructureVerbMask_index_0[i+1]]
	case i == 4:
		return _ModelChangeStructureVerbMask_name_1
	case i == 8:
		return _ModelChangeStructureVerbMask_name_2
	case i == 16:
		return _ModelChangeStructureVerbMask_name_3
	default:
		return "ModelChangeStructureVerbMask(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AxisScaleEnumerationLinear-0]
	_ = x[AxisScaleEnumerationLog-1]
	_ = x[AxisScaleEnumerationLn-2]
}

const _AxisScaleEnumeration_name = "AxisScaleEnumerationLinearAxisScaleEnumerationLogAxisScaleEnumerationLn"

var _AxisScaleEnumeration_index = [...]uint8{0, 26, 49, 71}

func (i AxisScaleEnumeration) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AxisScaleEnumeration_index)-1 {
		return "AxisScaleEnumeration(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AxisScaleEnumeration_name[_AxisScaleEnumeration_index[idx]:_AxisScaleEnumeration_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExceptionDeviationFormatAbsoluteValue-0]
	_ = x[ExceptionDeviationFormatPercentOfValue-1]
	_ = x[ExceptionDeviationFormatPercentOfRange-2]
	_ = x[ExceptionDeviationFormatPercentOfEURange-3]
	_ = x[ExceptionDeviationFormatUnknown-4]
}

const _ExceptionDeviationFormat_name = "ExceptionDeviationFormatAbsoluteValueExceptionDeviationFormatPercentOfValueExceptionDeviationFormatPercentOfRangeExceptionDeviationFormatPercentOfEURangeExceptionDeviationFormatUnknown"

var _ExceptionDeviationFormat_index = [...]uint8{0, 37, 75, 113, 153, 184}

func (i ExceptionDeviationFormat) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ExceptionDeviationFormat_index)-1 {
		return "ExceptionDeviationFormat(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExceptionDeviationFormat_name[_ExceptionDeviationFormat_index[idx]:_ExceptionDeviationFormat_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AttributeIDInvalid-0]
	_ = x[AttributeIDNodeID-1]
	_ = x[AttributeIDNodeClass-2]
	_ = x[AttributeIDBrowseName-3]
	_ = x[AttributeIDDisplayName-4]
	_ = x[AttributeIDDescription-5]
	_ = x[AttributeIDWriteMask-6]
	_ = x[AttributeIDUserWriteMask-7]
	_ = x[AttributeIDIsAbstract-8]
	_ = x[AttributeIDSymmetric-9]
	_ = x[AttributeIDInverseName-10]
	_ = x[AttributeIDContainsNoLoops-11]
	_ = x[AttributeIDEventNotifier-12]
	_ = x[AttributeIDValue-13]
	_ = x[AttributeIDDataType-14]
	_ = x[AttributeIDValueRank-15]
	_ = x[AttributeIDArrayDimensions-16]
	_ = x[AttributeIDAccessLevel-17]
	_ = x[AttributeIDUserAccessLevel-18]
	_ = x[AttributeIDMinimumSamplingInterval-19]
	_ = x[AttributeIDHistorizing-20]
	_ = x[AttributeIDExecutable-21]
	_ = x[AttributeIDUserExecutable-22]
	_ = x[AttributeIDDataTypeDefinition-23]
	_ = x[AttributeIDRolePermissions-24]
	_ = x[AttributeIDUserRolePermissions-25]
	_ = x[AttributeIDAccessRestrictions-26]
	_ = x[AttributeIDAccessLevelEx-27]
}

const _AttributeID_name = "AttributeIDInvalidAttributeIDNodeIDAttributeIDNodeClassAttributeIDBrowseNameAttributeIDDisplayNameAttributeIDDescriptionAttributeIDWriteMaskAttributeIDUserWriteMaskAttributeIDIsAbstractAttributeIDSymmetricAttributeIDInverseNameAttributeIDContainsNoLoopsAttributeIDEventNotifierAttributeIDValueAttributeIDDataTypeAttributeIDValueRankAttributeIDArrayDimensionsAttributeIDAccessLevelAttributeIDUserAccessLevelAttributeIDMinimumSamplingIntervalAttributeIDHistorizingAttributeIDExecutableAttributeIDUserExecutableAttributeIDDataTypeDefinitionAttributeIDRolePermissionsAttributeIDUserRolePermissionsAttributeIDAccessRestrictionsAttributeIDAccessLevelEx"

var _AttributeID_index = [...]uint16{0, 18, 35, 55, 76, 98, 120, 140, 164, 185, 205, 227, 253, 277, 293, 312, 332, 358, 380, 406, 440, 462, 483, 508, 537, 563, 593, 622, 646}

func (i AttributeID) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AttributeID_index)-1 {
		return "AttributeID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AttributeID_name[_AttributeID_index[idx]:_AttributeID_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeIDNull-0]
	_ = x[TypeIDBoolean-1]
	_ = x[TypeIDSByte-2]
	_ = x[TypeIDByte-3]
	_ = x[TypeIDInt16-4]
	_ = x[TypeIDUint16-5]
	_ = x[TypeIDInt32-6]
	_ = x[TypeIDUint32-7]
	_ = x[TypeIDInt64-8]
	_ = x[TypeIDUint64-9]
	_ = x[TypeIDFloat-10]
	_ = x[TypeIDDouble-11]
	_ = x[TypeIDString-12]
	_ = x[TypeIDDateTime-13]
	_ = x[TypeIDGUID-14]
	_ = x[TypeIDByteString-15]
	_ = x[TypeIDXMLElement-16]
	_ = x[TypeIDNodeID-17]
	_ = x[TypeIDExpandedNodeID-18]
	_ = x[TypeIDStatusCode-19]
	_ = x[TypeIDQualifiedName-20]
	_ = x[TypeIDLocalizedText-21]
	_ = x[TypeIDExtensionObject-22]
	_ = x[TypeIDDataValue-23]
	_ = x[TypeIDVariant-24]
	_ = x[TypeIDDiagnosticInfo-25]
}

const _TypeID_name = "TypeIDNullTypeIDBooleanTypeIDSByteTypeIDByteTypeIDInt16TypeIDUint16TypeIDInt32TypeIDUint32TypeIDInt64TypeIDUint64TypeIDFloatTypeIDDoubleTypeIDStringTypeIDDateTimeTypeIDGUIDTypeIDByteStringTypeIDXMLElementTypeIDNodeIDTypeIDExpandedNodeIDTypeIDStatusCodeTypeIDQualifiedNameTypeIDLocalizedTextTypeIDExtensionObjectTypeIDDataValueTypeIDVariantTypeIDDiagnosticInfo"

var _TypeID_index = [...]uint16{0, 10, 23, 34, 44, 55, 67, 78, 90, 101, 113, 124, 136, 148, 162, 172, 188, 204, 216, 236, 252, 271, 290, 311, 326, 339, 359}

func (i TypeID) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TypeID_index)-1 {
		return "TypeID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TypeID_name[_TypeID_index[idx]:_TypeID_index[idx+1]]
}
