// Copyright 2018-2024 opcua authors. All rights reserved.
// Use of this source code is governed by a MIT-style license that can be
// found in the LICENSE file.

// Code generated by cmd/capability. DO NOT EDIT!

package ua

// Server capability profile identifiers per OPC UA specification.
const (
	// CapabilityNA: No capability information is available. Cannot be used in combination with any other capability.
	CapabilityNA = "NA"
	// CapabilityDA: Provides current data.
	CapabilityDA = "DA"
	// CapabilityHD: Provides historical data.
	CapabilityHD = "HD"
	// CapabilityAC: Provides alarms and conditions that may require operator interaction.
	CapabilityAC = "AC"
	// CapabilityHE: Provides historical alarms and events.
	CapabilityHE = "HE"
	// CapabilityGDS: Supports the Global Discovery Server information model.
	CapabilityGDS = "GDS"
	// CapabilityLDS: Only supports the Discovery Services. Cannot be used in combination with any other capability.
	CapabilityLDS = "LDS"
	// CapabilityDI: Supports the Device Integration (DI) information model (see DI).
	CapabilityDI = "DI"
	// CapabilityADI: Supports the Analyser Device Integration (ADI) information model (see ADI).
	CapabilityADI = "ADI"
	// CapabilityFDI: Supports the Field Device Integration (FDI) information model (see FDI).
	CapabilityFDI = "FDI"
	// CapabilityFDIC: Supports the Field Device Integration (FDI) Communication Server information model (see FDI).
	CapabilityFDIC = "FDIC"
	// CapabilityPLC: Supports the PLCopen information model (see PLCopen).
	CapabilityPLC = "PLC"
	// CapabilityS95: Supports the ISA95 information model (see ISA-95).
	CapabilityS95 = "S95"
	// CapabilityRCP: Supports the reverse connect capabilities defined in Part 6.
	CapabilityRCP = "RCP"
	// CapabilityPUB: Supports the Publisher capabilities defined in Part 14.
	CapabilityPUB = "PUB"
	// CapabilityNTRS: The server is part of a non-transparent redundant server set defined in Part 4.
	CapabilityNTRS = "NTRS"
	// CapabilityAUTOID: Supports the AutoID information model.
	CapabilityAUTOID = "AUTOID"
	// CapabilityMDIS: Supports the MDIS information model.
	CapabilityMDIS = "MDIS"
	// CapabilityCNC: Supports the information model for Computerized Numerical Control (CNC) systems.
	CapabilityCNC = "CNC"
	// CapabilityPLK: Supports the POWERLINK information model.
	CapabilityPLK = "PLK"
	// CapabilityFDT: Supports the FDT information model.
	CapabilityFDT = "FDT"
	// CapabilityTMC: Supports the Tobacco Machine Communication (TMC) information model.
	CapabilityTMC = "TMC"
	// CapabilityCSPP: Supports the CSP+ device profile (CSPPlusForMachine) information model.
	CapabilityCSPP = "CSPP"
	// CapabilityIEC61850: Supports the IEC61850 information model.
	CapabilityIEC61850 = "61850"
	// CapabilityPACKML: Supports the PackML information model.
	CapabilityPACKML = "PACKML"
	// CapabilityMTC: Supports the MTConnect information model.
	CapabilityMTC = "MTC"
	// CapabilityAUTOML: Supports the AutomationML information model.
	CapabilityAUTOML = "AUTOML"
	// CapabilitySERCOS: Supports the Sercos information model.
	CapabilitySERCOS = "SERCOS"
	// CapabilityMIMOSA: Supports the MIMOSA information model.
	CapabilityMIMOSA = "MIMOSA"
	// CapabilityWITSML: Supports the WITSML information model.
	CapabilityWITSML = "WITSML"
	// CapabilityDEXPI: Supports the DEXPI information model.
	CapabilityDEXPI = "DEXPI"
	// CapabilityIOLINK: Supports the IOLINK information model.
	CapabilityIOLINK = "IOLINK"
	// CapabilityVROBOT: Supports the VDMA ROBOTICS information model.
	CapabilityVROBOT = "VROBOT"
	// CapabilityPNO: Supports the ProfiNET information model.
	CapabilityPNO = "PNO"
	// CapabilityPADIM: Supports the information model for Process Automation Devices.
	CapabilityPADIM = "PADIM"
	// CapabilityALIAS: Supports the AliasNames capabilities.
	CapabilityALIAS = "ALIAS"
	// CapabilitySKS: Supports the Security Key Servers (SKS) capabilities.
	CapabilitySKS = "SKS"
	// CapabilityFXAC: Supports the UA FX Automation Component information model.
	CapabilityFXAC = "FXAC"
	// CapabilityFXCM: Supports the UA FX Connection Manager information model.
	CapabilityFXCM = "FXCM"
)

// KnownCapabilities maps server capability identifiers to their descriptions.
var KnownCapabilities = map[string]string{
	CapabilityNA:       "No capability information is available. Cannot be used in combination with any other capability.",
	CapabilityDA:       "Provides current data.",
	CapabilityHD:       "Provides historical data.",
	CapabilityAC:       "Provides alarms and conditions that may require operator interaction.",
	CapabilityHE:       "Provides historical alarms and events.",
	CapabilityGDS:      "Supports the Global Discovery Server information model.",
	CapabilityLDS:      "Only supports the Discovery Services. Cannot be used in combination with any other capability.",
	CapabilityDI:       "Supports the Device Integration (DI) information model (see DI).",
	CapabilityADI:      "Supports the Analyser Device Integration (ADI) information model (see ADI).",
	CapabilityFDI:      "Supports the Field Device Integration (FDI) information model (see FDI).",
	CapabilityFDIC:     "Supports the Field Device Integration (FDI) Communication Server information model (see FDI).",
	CapabilityPLC:      "Supports the PLCopen information model (see PLCopen).",
	CapabilityS95:      "Supports the ISA95 information model (see ISA-95).",
	CapabilityRCP:      "Supports the reverse connect capabilities defined in Part 6.",
	CapabilityPUB:      "Supports the Publisher capabilities defined in Part 14.",
	CapabilityNTRS:     "The server is part of a non-transparent redundant server set defined in Part 4.",
	CapabilityAUTOID:   "Supports the AutoID information model.",
	CapabilityMDIS:     "Supports the MDIS information model.",
	CapabilityCNC:      "Supports the information model for Computerized Numerical Control (CNC) systems.",
	CapabilityPLK:      "Supports the POWERLINK information model.",
	CapabilityFDT:      "Supports the FDT information model.",
	CapabilityTMC:      "Supports the Tobacco Machine Communication (TMC) information model.",
	CapabilityCSPP:     "Supports the CSP+ device profile (CSPPlusForMachine) information model.",
	CapabilityIEC61850: "Supports the IEC61850 information model.",
	CapabilityPACKML:   "Supports the PackML information model.",
	CapabilityMTC:      "Supports the MTConnect information model.",
	CapabilityAUTOML:   "Supports the AutomationML information model.",
	CapabilitySERCOS:   "Supports the Sercos information model.",
	CapabilityMIMOSA:   "Supports the MIMOSA information model.",
	CapabilityWITSML:   "Supports the WITSML information model.",
	CapabilityDEXPI:    "Supports the DEXPI information model.",
	CapabilityIOLINK:   "Supports the IOLINK information model.",
	CapabilityVROBOT:   "Supports the VDMA ROBOTICS information model.",
	CapabilityPNO:      "Supports the ProfiNET information model.",
	CapabilityPADIM:    "Supports the information model for Process Automation Devices.",
	CapabilityALIAS:    "Supports the AliasNames capabilities.",
	CapabilitySKS:      "Supports the Security Key Servers (SKS) capabilities.",
	CapabilityFXAC:     "Supports the UA FX Automation Component information model.",
	CapabilityFXCM:     "Supports the UA FX Connection Manager information model.",
}

// ValidateCapability reports whether s is a known server capability identifier.
func ValidateCapability(s string) bool {
	_, ok := KnownCapabilities[s]
	return ok
}
